/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DestinationsRouteImport } from './routes/destinations'
import { Route as CreateRouteImport } from './routes/create'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as DestinationsCountryRouteImport } from './routes/destinations.$country'
import { Route as CollectionsIdRouteImport } from './routes/collections.$id'
import { Route as DestinationsCountryCityRouteImport } from './routes/destinations.$country.$city'
import { Route as ApiPublicMuxWebhookRouteImport } from './routes/api/public/mux-webhook'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsRoute = DestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsCountryRoute = DestinationsCountryRouteImport.update({
  id: '/$country',
  path: '/$country',
  getParentRoute: () => DestinationsRoute,
} as any)
const CollectionsIdRoute = CollectionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CollectionsRoute,
} as any)
const DestinationsCountryCityRoute = DestinationsCountryCityRouteImport.update({
  id: '/$city',
  path: '/$city',
  getParentRoute: () => DestinationsCountryRoute,
} as any)
const ApiPublicMuxWebhookRoute = ApiPublicMuxWebhookRouteImport.update({
  id: '/api/public/mux-webhook',
  path: '/api/public/mux-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/create': typeof CreateRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/collections/$id': typeof CollectionsIdRoute
  '/destinations/$country': typeof DestinationsCountryRouteWithChildren
  '/u/$username': typeof UUsernameRoute
  '/api/public/mux-webhook': typeof ApiPublicMuxWebhookRoute
  '/destinations/$country/$city': typeof DestinationsCountryCityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/create': typeof CreateRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/collections/$id': typeof CollectionsIdRoute
  '/destinations/$country': typeof DestinationsCountryRouteWithChildren
  '/u/$username': typeof UUsernameRoute
  '/api/public/mux-webhook': typeof ApiPublicMuxWebhookRoute
  '/destinations/$country/$city': typeof DestinationsCountryCityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/create': typeof CreateRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/collections/$id': typeof CollectionsIdRoute
  '/destinations/$country': typeof DestinationsCountryRouteWithChildren
  '/u/$username': typeof UUsernameRoute
  '/api/public/mux-webhook': typeof ApiPublicMuxWebhookRoute
  '/destinations/$country/$city': typeof DestinationsCountryCityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/collections'
    | '/create'
    | '/destinations'
    | '/login'
    | '/profile'
    | '/search'
    | '/collections/$id'
    | '/destinations/$country'
    | '/u/$username'
    | '/api/public/mux-webhook'
    | '/destinations/$country/$city'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/collections'
    | '/create'
    | '/destinations'
    | '/login'
    | '/profile'
    | '/search'
    | '/collections/$id'
    | '/destinations/$country'
    | '/u/$username'
    | '/api/public/mux-webhook'
    | '/destinations/$country/$city'
  id:
    | '__root__'
    | '/'
    | '/collections'
    | '/create'
    | '/destinations'
    | '/login'
    | '/profile'
    | '/search'
    | '/collections/$id'
    | '/destinations/$country'
    | '/u/$username'
    | '/api/public/mux-webhook'
    | '/destinations/$country/$city'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollectionsRoute: typeof CollectionsRouteWithChildren
  CreateRoute: typeof CreateRoute
  DestinationsRoute: typeof DestinationsRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  UUsernameRoute: typeof UUsernameRoute
  ApiPublicMuxWebhookRoute: typeof ApiPublicMuxWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations': {
      id: '/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof DestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/$country': {
      id: '/destinations/$country'
      path: '/$country'
      fullPath: '/destinations/$country'
      preLoaderRoute: typeof DestinationsCountryRouteImport
      parentRoute: typeof DestinationsRoute
    }
    '/collections/$id': {
      id: '/collections/$id'
      path: '/$id'
      fullPath: '/collections/$id'
      preLoaderRoute: typeof CollectionsIdRouteImport
      parentRoute: typeof CollectionsRoute
    }
    '/destinations/$country/$city': {
      id: '/destinations/$country/$city'
      path: '/$city'
      fullPath: '/destinations/$country/$city'
      preLoaderRoute: typeof DestinationsCountryCityRouteImport
      parentRoute: typeof DestinationsCountryRoute
    }
    '/api/public/mux-webhook': {
      id: '/api/public/mux-webhook'
      path: '/api/public/mux-webhook'
      fullPath: '/api/public/mux-webhook'
      preLoaderRoute: typeof ApiPublicMuxWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CollectionsRouteChildren {
  CollectionsIdRoute: typeof CollectionsIdRoute
}

const CollectionsRouteChildren: CollectionsRouteChildren = {
  CollectionsIdRoute: CollectionsIdRoute,
}

const CollectionsRouteWithChildren = CollectionsRoute._addFileChildren(
  CollectionsRouteChildren,
)

interface DestinationsCountryRouteChildren {
  DestinationsCountryCityRoute: typeof DestinationsCountryCityRoute
}

const DestinationsCountryRouteChildren: DestinationsCountryRouteChildren = {
  DestinationsCountryCityRoute: DestinationsCountryCityRoute,
}

const DestinationsCountryRouteWithChildren =
  DestinationsCountryRoute._addFileChildren(DestinationsCountryRouteChildren)

interface DestinationsRouteChildren {
  DestinationsCountryRoute: typeof DestinationsCountryRouteWithChildren
}

const DestinationsRouteChildren: DestinationsRouteChildren = {
  DestinationsCountryRoute: DestinationsCountryRouteWithChildren,
}

const DestinationsRouteWithChildren = DestinationsRoute._addFileChildren(
  DestinationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectionsRoute: CollectionsRouteWithChildren,
  CreateRoute: CreateRoute,
  DestinationsRoute: DestinationsRouteWithChildren,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  UUsernameRoute: UUsernameRoute,
  ApiPublicMuxWebhookRoute: ApiPublicMuxWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
