/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as SupportRouteImport } from './routes/support'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MapRouteImport } from './routes/map'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CreateRouteImport } from './routes/create'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudioIndexRouteImport } from './routes/studio.index'
import { Route as LegalIndexRouteImport } from './routes/legal.index'
import { Route as ItinerariesIndexRouteImport } from './routes/itineraries.index'
import { Route as DestinationsIndexRouteImport } from './routes/destinations.index'
import { Route as DealsIndexRouteImport } from './routes/deals.index'
import { Route as BusinessIndexRouteImport } from './routes/business.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as StudioVideosRouteImport } from './routes/studio.videos'
import { Route as StudioScheduleRouteImport } from './routes/studio.schedule'
import { Route as StudioLinksRouteImport } from './routes/studio.links'
import { Route as SoundsIdRouteImport } from './routes/sounds.$id'
import { Route as RCodeRouteImport } from './routes/r.$code'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as ItinerariesNewRouteImport } from './routes/itineraries.new'
import { Route as ItinerariesIdRouteImport } from './routes/itineraries.$id'
import { Route as DealsIdRouteImport } from './routes/deals.$id'
import { Route as CreatorApplicationsRouteImport } from './routes/creator.applications'
import { Route as CreatorAnalyticsRouteImport } from './routes/creator.analytics'
import { Route as CollectionsIdRouteImport } from './routes/collections.$id'
import { Route as BusinessCalculatorRouteImport } from './routes/business.calculator'
import { Route as BusinessApplyRouteImport } from './routes/business.apply'
import { Route as BusinessApplicationsRouteImport } from './routes/business.applications'
import { Route as AdminVideosRouteImport } from './routes/admin.videos'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminModerationRouteImport } from './routes/admin.moderation'
import { Route as AdminDiscoveriesRouteImport } from './routes/admin.discoveries'
import { Route as AdminDealsRouteImport } from './routes/admin.deals'
import { Route as DestinationsCountryIndexRouteImport } from './routes/destinations.$country.index'
import { Route as StudioVideosIdRouteImport } from './routes/studio.videos.$id'
import { Route as DestinationsCountryCityRouteImport } from './routes/destinations.$country.$city'
import { Route as BusinessInviteTokenRouteImport } from './routes/business.invite.$token'
import { Route as BusinessDealsNewRouteImport } from './routes/business.deals.new'
import { Route as BusinessDealsIdRouteImport } from './routes/business.deals.$id'
import { Route as ApiPublicMuxWebhookRouteImport } from './routes/api/public/mux-webhook'
import { Route as BusinessDealsIdIndexRouteImport } from './routes/business.deals.$id.index'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as BusinessDealsIdEditRouteImport } from './routes/business.deals.$id.edit'
import { Route as ApiPublicGoIdRouteImport } from './routes/api/public/go.$id'
import { Route as ApiPublicDIdRouteImport } from './routes/api/public/d.$id'
import { Route as ApiPublicCronDiscoverDealsRouteImport } from './routes/api/public/cron/discover-deals'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioRoute,
} as any)
const LegalIndexRoute = LegalIndexRouteImport.update({
  id: '/legal/',
  path: '/legal/',
  getParentRoute: () => rootRouteImport,
} as any)
const ItinerariesIndexRoute = ItinerariesIndexRouteImport.update({
  id: '/itineraries/',
  path: '/itineraries/',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsIndexRoute = DestinationsIndexRouteImport.update({
  id: '/destinations/',
  path: '/destinations/',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsIndexRoute = DealsIndexRouteImport.update({
  id: '/deals/',
  path: '/deals/',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessIndexRoute = BusinessIndexRouteImport.update({
  id: '/business/',
  path: '/business/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioVideosRoute = StudioVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => StudioRoute,
} as any)
const StudioScheduleRoute = StudioScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => StudioRoute,
} as any)
const StudioLinksRoute = StudioLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => StudioRoute,
} as any)
const SoundsIdRoute = SoundsIdRouteImport.update({
  id: '/sounds/$id',
  path: '/sounds/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RCodeRoute = RCodeRouteImport.update({
  id: '/r/$code',
  path: '/r/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ItinerariesNewRoute = ItinerariesNewRouteImport.update({
  id: '/itineraries/new',
  path: '/itineraries/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ItinerariesIdRoute = ItinerariesIdRouteImport.update({
  id: '/itineraries/$id',
  path: '/itineraries/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsIdRoute = DealsIdRouteImport.update({
  id: '/deals/$id',
  path: '/deals/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorApplicationsRoute = CreatorApplicationsRouteImport.update({
  id: '/creator/applications',
  path: '/creator/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorAnalyticsRoute = CreatorAnalyticsRouteImport.update({
  id: '/creator/analytics',
  path: '/creator/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIdRoute = CollectionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CollectionsRoute,
} as any)
const BusinessCalculatorRoute = BusinessCalculatorRouteImport.update({
  id: '/business/calculator',
  path: '/business/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessApplyRoute = BusinessApplyRouteImport.update({
  id: '/business/apply',
  path: '/business/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessApplicationsRoute = BusinessApplicationsRouteImport.update({
  id: '/business/applications',
  path: '/business/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVideosRoute = AdminVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModerationRoute = AdminModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDiscoveriesRoute = AdminDiscoveriesRouteImport.update({
  id: '/discoveries',
  path: '/discoveries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDealsRoute = AdminDealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => AdminRoute,
} as any)
const DestinationsCountryIndexRoute =
  DestinationsCountryIndexRouteImport.update({
    id: '/destinations/$country/',
    path: '/destinations/$country/',
    getParentRoute: () => rootRouteImport,
  } as any)
const StudioVideosIdRoute = StudioVideosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StudioVideosRoute,
} as any)
const DestinationsCountryCityRoute = DestinationsCountryCityRouteImport.update({
  id: '/destinations/$country/$city',
  path: '/destinations/$country/$city',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessInviteTokenRoute = BusinessInviteTokenRouteImport.update({
  id: '/business/invite/$token',
  path: '/business/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessDealsNewRoute = BusinessDealsNewRouteImport.update({
  id: '/business/deals/new',
  path: '/business/deals/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessDealsIdRoute = BusinessDealsIdRouteImport.update({
  id: '/business/deals/$id',
  path: '/business/deals/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMuxWebhookRoute = ApiPublicMuxWebhookRouteImport.update({
  id: '/api/public/mux-webhook',
  path: '/api/public/mux-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessDealsIdIndexRoute = BusinessDealsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BusinessDealsIdRoute,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessDealsIdEditRoute = BusinessDealsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => BusinessDealsIdRoute,
} as any)
const ApiPublicGoIdRoute = ApiPublicGoIdRouteImport.update({
  id: '/api/public/go/$id',
  path: '/api/public/go/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDIdRoute = ApiPublicDIdRouteImport.update({
  id: '/api/public/d/$id',
  path: '/api/public/d/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronDiscoverDealsRoute =
  ApiPublicCronDiscoverDealsRouteImport.update({
    id: '/api/public/cron/discover-deals',
    path: '/api/public/cron/discover-deals',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/collections': typeof CollectionsRouteWithChildren
  '/create': typeof CreateRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/studio': typeof StudioRouteWithChildren
  '/support': typeof SupportRoute
  '/welcome': typeof WelcomeRoute
  '/admin/deals': typeof AdminDealsRoute
  '/admin/discoveries': typeof AdminDiscoveriesRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/videos': typeof AdminVideosRoute
  '/business/applications': typeof BusinessApplicationsRoute
  '/business/apply': typeof BusinessApplyRoute
  '/business/calculator': typeof BusinessCalculatorRoute
  '/collections/$id': typeof CollectionsIdRoute
  '/creator/analytics': typeof CreatorAnalyticsRoute
  '/creator/applications': typeof CreatorApplicationsRoute
  '/deals/$id': typeof DealsIdRoute
  '/itineraries/$id': typeof ItinerariesIdRoute
  '/itineraries/new': typeof ItinerariesNewRoute
  '/legal/terms': typeof LegalTermsRoute
  '/r/$code': typeof RCodeRoute
  '/sounds/$id': typeof SoundsIdRoute
  '/studio/links': typeof StudioLinksRoute
  '/studio/schedule': typeof StudioScheduleRoute
  '/studio/videos': typeof StudioVideosRouteWithChildren
  '/u/$username': typeof UUsernameRoute
  '/admin/': typeof AdminIndexRoute
  '/business/': typeof BusinessIndexRoute
  '/deals/': typeof DealsIndexRoute
  '/destinations/': typeof DestinationsIndexRoute
  '/itineraries/': typeof ItinerariesIndexRoute
  '/legal/': typeof LegalIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/api/public/mux-webhook': typeof ApiPublicMuxWebhookRoute
  '/business/deals/$id': typeof BusinessDealsIdRouteWithChildren
  '/business/deals/new': typeof BusinessDealsNewRoute
  '/business/invite/$token': typeof BusinessInviteTokenRoute
  '/destinations/$country/$city': typeof DestinationsCountryCityRoute
  '/studio/videos/$id': typeof StudioVideosIdRoute
  '/destinations/$country/': typeof DestinationsCountryIndexRoute
  '/api/public/cron/discover-deals': typeof ApiPublicCronDiscoverDealsRoute
  '/api/public/d/$id': typeof ApiPublicDIdRoute
  '/api/public/go/$id': typeof ApiPublicGoIdRoute
  '/business/deals/$id/edit': typeof BusinessDealsIdEditRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/business/deals/$id/': typeof BusinessDealsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/create': typeof CreateRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/support': typeof SupportRoute
  '/welcome': typeof WelcomeRoute
  '/admin/deals': typeof AdminDealsRoute
  '/admin/discoveries': typeof AdminDiscoveriesRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/videos': typeof AdminVideosRoute
  '/business/applications': typeof BusinessApplicationsRoute
  '/business/apply': typeof BusinessApplyRoute
  '/business/calculator': typeof BusinessCalculatorRoute
  '/collections/$id': typeof CollectionsIdRoute
  '/creator/analytics': typeof CreatorAnalyticsRoute
  '/creator/applications': typeof CreatorApplicationsRoute
  '/deals/$id': typeof DealsIdRoute
  '/itineraries/$id': typeof ItinerariesIdRoute
  '/itineraries/new': typeof ItinerariesNewRoute
  '/legal/terms': typeof LegalTermsRoute
  '/r/$code': typeof RCodeRoute
  '/sounds/$id': typeof SoundsIdRoute
  '/studio/links': typeof StudioLinksRoute
  '/studio/schedule': typeof StudioScheduleRoute
  '/studio/videos': typeof StudioVideosRouteWithChildren
  '/u/$username': typeof UUsernameRoute
  '/admin': typeof AdminIndexRoute
  '/business': typeof BusinessIndexRoute
  '/deals': typeof DealsIndexRoute
  '/destinations': typeof DestinationsIndexRoute
  '/itineraries': typeof ItinerariesIndexRoute
  '/legal': typeof LegalIndexRoute
  '/studio': typeof StudioIndexRoute
  '/api/public/mux-webhook': typeof ApiPublicMuxWebhookRoute
  '/business/deals/new': typeof BusinessDealsNewRoute
  '/business/invite/$token': typeof BusinessInviteTokenRoute
  '/destinations/$country/$city': typeof DestinationsCountryCityRoute
  '/studio/videos/$id': typeof StudioVideosIdRoute
  '/destinations/$country': typeof DestinationsCountryIndexRoute
  '/api/public/cron/discover-deals': typeof ApiPublicCronDiscoverDealsRoute
  '/api/public/d/$id': typeof ApiPublicDIdRoute
  '/api/public/go/$id': typeof ApiPublicGoIdRoute
  '/business/deals/$id/edit': typeof BusinessDealsIdEditRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/business/deals/$id': typeof BusinessDealsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/collections': typeof CollectionsRouteWithChildren
  '/create': typeof CreateRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/studio': typeof StudioRouteWithChildren
  '/support': typeof SupportRoute
  '/welcome': typeof WelcomeRoute
  '/admin/deals': typeof AdminDealsRoute
  '/admin/discoveries': typeof AdminDiscoveriesRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/videos': typeof AdminVideosRoute
  '/business/applications': typeof BusinessApplicationsRoute
  '/business/apply': typeof BusinessApplyRoute
  '/business/calculator': typeof BusinessCalculatorRoute
  '/collections/$id': typeof CollectionsIdRoute
  '/creator/analytics': typeof CreatorAnalyticsRoute
  '/creator/applications': typeof CreatorApplicationsRoute
  '/deals/$id': typeof DealsIdRoute
  '/itineraries/$id': typeof ItinerariesIdRoute
  '/itineraries/new': typeof ItinerariesNewRoute
  '/legal/terms': typeof LegalTermsRoute
  '/r/$code': typeof RCodeRoute
  '/sounds/$id': typeof SoundsIdRoute
  '/studio/links': typeof StudioLinksRoute
  '/studio/schedule': typeof StudioScheduleRoute
  '/studio/videos': typeof StudioVideosRouteWithChildren
  '/u/$username': typeof UUsernameRoute
  '/admin/': typeof AdminIndexRoute
  '/business/': typeof BusinessIndexRoute
  '/deals/': typeof DealsIndexRoute
  '/destinations/': typeof DestinationsIndexRoute
  '/itineraries/': typeof ItinerariesIndexRoute
  '/legal/': typeof LegalIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/api/public/mux-webhook': typeof ApiPublicMuxWebhookRoute
  '/business/deals/$id': typeof BusinessDealsIdRouteWithChildren
  '/business/deals/new': typeof BusinessDealsNewRoute
  '/business/invite/$token': typeof BusinessInviteTokenRoute
  '/destinations/$country/$city': typeof DestinationsCountryCityRoute
  '/studio/videos/$id': typeof StudioVideosIdRoute
  '/destinations/$country/': typeof DestinationsCountryIndexRoute
  '/api/public/cron/discover-deals': typeof ApiPublicCronDiscoverDealsRoute
  '/api/public/d/$id': typeof ApiPublicDIdRoute
  '/api/public/go/$id': typeof ApiPublicGoIdRoute
  '/business/deals/$id/edit': typeof BusinessDealsIdEditRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/business/deals/$id/': typeof BusinessDealsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/collections'
    | '/create'
    | '/login'
    | '/map'
    | '/notifications'
    | '/profile'
    | '/reset-password'
    | '/search'
    | '/studio'
    | '/support'
    | '/welcome'
    | '/admin/deals'
    | '/admin/discoveries'
    | '/admin/moderation'
    | '/admin/users'
    | '/admin/videos'
    | '/business/applications'
    | '/business/apply'
    | '/business/calculator'
    | '/collections/$id'
    | '/creator/analytics'
    | '/creator/applications'
    | '/deals/$id'
    | '/itineraries/$id'
    | '/itineraries/new'
    | '/legal/terms'
    | '/r/$code'
    | '/sounds/$id'
    | '/studio/links'
    | '/studio/schedule'
    | '/studio/videos'
    | '/u/$username'
    | '/admin/'
    | '/business/'
    | '/deals/'
    | '/destinations/'
    | '/itineraries/'
    | '/legal/'
    | '/studio/'
    | '/api/public/mux-webhook'
    | '/business/deals/$id'
    | '/business/deals/new'
    | '/business/invite/$token'
    | '/destinations/$country/$city'
    | '/studio/videos/$id'
    | '/destinations/$country/'
    | '/api/public/cron/discover-deals'
    | '/api/public/d/$id'
    | '/api/public/go/$id'
    | '/business/deals/$id/edit'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/business/deals/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/collections'
    | '/create'
    | '/login'
    | '/map'
    | '/notifications'
    | '/profile'
    | '/reset-password'
    | '/search'
    | '/support'
    | '/welcome'
    | '/admin/deals'
    | '/admin/discoveries'
    | '/admin/moderation'
    | '/admin/users'
    | '/admin/videos'
    | '/business/applications'
    | '/business/apply'
    | '/business/calculator'
    | '/collections/$id'
    | '/creator/analytics'
    | '/creator/applications'
    | '/deals/$id'
    | '/itineraries/$id'
    | '/itineraries/new'
    | '/legal/terms'
    | '/r/$code'
    | '/sounds/$id'
    | '/studio/links'
    | '/studio/schedule'
    | '/studio/videos'
    | '/u/$username'
    | '/admin'
    | '/business'
    | '/deals'
    | '/destinations'
    | '/itineraries'
    | '/legal'
    | '/studio'
    | '/api/public/mux-webhook'
    | '/business/deals/new'
    | '/business/invite/$token'
    | '/destinations/$country/$city'
    | '/studio/videos/$id'
    | '/destinations/$country'
    | '/api/public/cron/discover-deals'
    | '/api/public/d/$id'
    | '/api/public/go/$id'
    | '/business/deals/$id/edit'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/business/deals/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/collections'
    | '/create'
    | '/login'
    | '/map'
    | '/notifications'
    | '/profile'
    | '/reset-password'
    | '/search'
    | '/studio'
    | '/support'
    | '/welcome'
    | '/admin/deals'
    | '/admin/discoveries'
    | '/admin/moderation'
    | '/admin/users'
    | '/admin/videos'
    | '/business/applications'
    | '/business/apply'
    | '/business/calculator'
    | '/collections/$id'
    | '/creator/analytics'
    | '/creator/applications'
    | '/deals/$id'
    | '/itineraries/$id'
    | '/itineraries/new'
    | '/legal/terms'
    | '/r/$code'
    | '/sounds/$id'
    | '/studio/links'
    | '/studio/schedule'
    | '/studio/videos'
    | '/u/$username'
    | '/admin/'
    | '/business/'
    | '/deals/'
    | '/destinations/'
    | '/itineraries/'
    | '/legal/'
    | '/studio/'
    | '/api/public/mux-webhook'
    | '/business/deals/$id'
    | '/business/deals/new'
    | '/business/invite/$token'
    | '/destinations/$country/$city'
    | '/studio/videos/$id'
    | '/destinations/$country/'
    | '/api/public/cron/discover-deals'
    | '/api/public/d/$id'
    | '/api/public/go/$id'
    | '/business/deals/$id/edit'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/business/deals/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CollectionsRoute: typeof CollectionsRouteWithChildren
  CreateRoute: typeof CreateRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  StudioRoute: typeof StudioRouteWithChildren
  SupportRoute: typeof SupportRoute
  WelcomeRoute: typeof WelcomeRoute
  BusinessApplicationsRoute: typeof BusinessApplicationsRoute
  BusinessApplyRoute: typeof BusinessApplyRoute
  BusinessCalculatorRoute: typeof BusinessCalculatorRoute
  CreatorAnalyticsRoute: typeof CreatorAnalyticsRoute
  CreatorApplicationsRoute: typeof CreatorApplicationsRoute
  DealsIdRoute: typeof DealsIdRoute
  ItinerariesIdRoute: typeof ItinerariesIdRoute
  ItinerariesNewRoute: typeof ItinerariesNewRoute
  LegalTermsRoute: typeof LegalTermsRoute
  RCodeRoute: typeof RCodeRoute
  SoundsIdRoute: typeof SoundsIdRoute
  UUsernameRoute: typeof UUsernameRoute
  BusinessIndexRoute: typeof BusinessIndexRoute
  DealsIndexRoute: typeof DealsIndexRoute
  DestinationsIndexRoute: typeof DestinationsIndexRoute
  ItinerariesIndexRoute: typeof ItinerariesIndexRoute
  LegalIndexRoute: typeof LegalIndexRoute
  ApiPublicMuxWebhookRoute: typeof ApiPublicMuxWebhookRoute
  BusinessDealsIdRoute: typeof BusinessDealsIdRouteWithChildren
  BusinessDealsNewRoute: typeof BusinessDealsNewRoute
  BusinessInviteTokenRoute: typeof BusinessInviteTokenRoute
  DestinationsCountryCityRoute: typeof DestinationsCountryCityRoute
  DestinationsCountryIndexRoute: typeof DestinationsCountryIndexRoute
  ApiPublicCronDiscoverDealsRoute: typeof ApiPublicCronDiscoverDealsRoute
  ApiPublicDIdRoute: typeof ApiPublicDIdRoute
  ApiPublicGoIdRoute: typeof ApiPublicGoIdRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof StudioRoute
    }
    '/legal/': {
      id: '/legal/'
      path: '/legal'
      fullPath: '/legal/'
      preLoaderRoute: typeof LegalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itineraries/': {
      id: '/itineraries/'
      path: '/itineraries'
      fullPath: '/itineraries/'
      preLoaderRoute: typeof ItinerariesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/': {
      id: '/destinations/'
      path: '/destinations'
      fullPath: '/destinations/'
      preLoaderRoute: typeof DestinationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals/': {
      id: '/deals/'
      path: '/deals'
      fullPath: '/deals/'
      preLoaderRoute: typeof DealsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/': {
      id: '/business/'
      path: '/business'
      fullPath: '/business/'
      preLoaderRoute: typeof BusinessIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/videos': {
      id: '/studio/videos'
      path: '/videos'
      fullPath: '/studio/videos'
      preLoaderRoute: typeof StudioVideosRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/schedule': {
      id: '/studio/schedule'
      path: '/schedule'
      fullPath: '/studio/schedule'
      preLoaderRoute: typeof StudioScheduleRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/links': {
      id: '/studio/links'
      path: '/links'
      fullPath: '/studio/links'
      preLoaderRoute: typeof StudioLinksRouteImport
      parentRoute: typeof StudioRoute
    }
    '/sounds/$id': {
      id: '/sounds/$id'
      path: '/sounds/$id'
      fullPath: '/sounds/$id'
      preLoaderRoute: typeof SoundsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$code': {
      id: '/r/$code'
      path: '/r/$code'
      fullPath: '/r/$code'
      preLoaderRoute: typeof RCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itineraries/new': {
      id: '/itineraries/new'
      path: '/itineraries/new'
      fullPath: '/itineraries/new'
      preLoaderRoute: typeof ItinerariesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itineraries/$id': {
      id: '/itineraries/$id'
      path: '/itineraries/$id'
      fullPath: '/itineraries/$id'
      preLoaderRoute: typeof ItinerariesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals/$id': {
      id: '/deals/$id'
      path: '/deals/$id'
      fullPath: '/deals/$id'
      preLoaderRoute: typeof DealsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/applications': {
      id: '/creator/applications'
      path: '/creator/applications'
      fullPath: '/creator/applications'
      preLoaderRoute: typeof CreatorApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/analytics': {
      id: '/creator/analytics'
      path: '/creator/analytics'
      fullPath: '/creator/analytics'
      preLoaderRoute: typeof CreatorAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$id': {
      id: '/collections/$id'
      path: '/$id'
      fullPath: '/collections/$id'
      preLoaderRoute: typeof CollectionsIdRouteImport
      parentRoute: typeof CollectionsRoute
    }
    '/business/calculator': {
      id: '/business/calculator'
      path: '/business/calculator'
      fullPath: '/business/calculator'
      preLoaderRoute: typeof BusinessCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/apply': {
      id: '/business/apply'
      path: '/business/apply'
      fullPath: '/business/apply'
      preLoaderRoute: typeof BusinessApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/applications': {
      id: '/business/applications'
      path: '/business/applications'
      fullPath: '/business/applications'
      preLoaderRoute: typeof BusinessApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/videos': {
      id: '/admin/videos'
      path: '/videos'
      fullPath: '/admin/videos'
      preLoaderRoute: typeof AdminVideosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/moderation': {
      id: '/admin/moderation'
      path: '/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AdminModerationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/discoveries': {
      id: '/admin/discoveries'
      path: '/discoveries'
      fullPath: '/admin/discoveries'
      preLoaderRoute: typeof AdminDiscoveriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/deals': {
      id: '/admin/deals'
      path: '/deals'
      fullPath: '/admin/deals'
      preLoaderRoute: typeof AdminDealsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/destinations/$country/': {
      id: '/destinations/$country/'
      path: '/destinations/$country'
      fullPath: '/destinations/$country/'
      preLoaderRoute: typeof DestinationsCountryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/videos/$id': {
      id: '/studio/videos/$id'
      path: '/$id'
      fullPath: '/studio/videos/$id'
      preLoaderRoute: typeof StudioVideosIdRouteImport
      parentRoute: typeof StudioVideosRoute
    }
    '/destinations/$country/$city': {
      id: '/destinations/$country/$city'
      path: '/destinations/$country/$city'
      fullPath: '/destinations/$country/$city'
      preLoaderRoute: typeof DestinationsCountryCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/invite/$token': {
      id: '/business/invite/$token'
      path: '/business/invite/$token'
      fullPath: '/business/invite/$token'
      preLoaderRoute: typeof BusinessInviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/deals/new': {
      id: '/business/deals/new'
      path: '/business/deals/new'
      fullPath: '/business/deals/new'
      preLoaderRoute: typeof BusinessDealsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/deals/$id': {
      id: '/business/deals/$id'
      path: '/business/deals/$id'
      fullPath: '/business/deals/$id'
      preLoaderRoute: typeof BusinessDealsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mux-webhook': {
      id: '/api/public/mux-webhook'
      path: '/api/public/mux-webhook'
      fullPath: '/api/public/mux-webhook'
      preLoaderRoute: typeof ApiPublicMuxWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/deals/$id/': {
      id: '/business/deals/$id/'
      path: '/'
      fullPath: '/business/deals/$id/'
      preLoaderRoute: typeof BusinessDealsIdIndexRouteImport
      parentRoute: typeof BusinessDealsIdRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/deals/$id/edit': {
      id: '/business/deals/$id/edit'
      path: '/edit'
      fullPath: '/business/deals/$id/edit'
      preLoaderRoute: typeof BusinessDealsIdEditRouteImport
      parentRoute: typeof BusinessDealsIdRoute
    }
    '/api/public/go/$id': {
      id: '/api/public/go/$id'
      path: '/api/public/go/$id'
      fullPath: '/api/public/go/$id'
      preLoaderRoute: typeof ApiPublicGoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/d/$id': {
      id: '/api/public/d/$id'
      path: '/api/public/d/$id'
      fullPath: '/api/public/d/$id'
      preLoaderRoute: typeof ApiPublicDIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/discover-deals': {
      id: '/api/public/cron/discover-deals'
      path: '/api/public/cron/discover-deals'
      fullPath: '/api/public/cron/discover-deals'
      preLoaderRoute: typeof ApiPublicCronDiscoverDealsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminDealsRoute: typeof AdminDealsRoute
  AdminDiscoveriesRoute: typeof AdminDiscoveriesRoute
  AdminModerationRoute: typeof AdminModerationRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVideosRoute: typeof AdminVideosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDealsRoute: AdminDealsRoute,
  AdminDiscoveriesRoute: AdminDiscoveriesRoute,
  AdminModerationRoute: AdminModerationRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVideosRoute: AdminVideosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CollectionsRouteChildren {
  CollectionsIdRoute: typeof CollectionsIdRoute
}

const CollectionsRouteChildren: CollectionsRouteChildren = {
  CollectionsIdRoute: CollectionsIdRoute,
}

const CollectionsRouteWithChildren = CollectionsRoute._addFileChildren(
  CollectionsRouteChildren,
)

interface StudioVideosRouteChildren {
  StudioVideosIdRoute: typeof StudioVideosIdRoute
}

const StudioVideosRouteChildren: StudioVideosRouteChildren = {
  StudioVideosIdRoute: StudioVideosIdRoute,
}

const StudioVideosRouteWithChildren = StudioVideosRoute._addFileChildren(
  StudioVideosRouteChildren,
)

interface StudioRouteChildren {
  StudioLinksRoute: typeof StudioLinksRoute
  StudioScheduleRoute: typeof StudioScheduleRoute
  StudioVideosRoute: typeof StudioVideosRouteWithChildren
  StudioIndexRoute: typeof StudioIndexRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioLinksRoute: StudioLinksRoute,
  StudioScheduleRoute: StudioScheduleRoute,
  StudioVideosRoute: StudioVideosRouteWithChildren,
  StudioIndexRoute: StudioIndexRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

interface BusinessDealsIdRouteChildren {
  BusinessDealsIdEditRoute: typeof BusinessDealsIdEditRoute
  BusinessDealsIdIndexRoute: typeof BusinessDealsIdIndexRoute
}

const BusinessDealsIdRouteChildren: BusinessDealsIdRouteChildren = {
  BusinessDealsIdEditRoute: BusinessDealsIdEditRoute,
  BusinessDealsIdIndexRoute: BusinessDealsIdIndexRoute,
}

const BusinessDealsIdRouteWithChildren = BusinessDealsIdRoute._addFileChildren(
  BusinessDealsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CollectionsRoute: CollectionsRouteWithChildren,
  CreateRoute: CreateRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  StudioRoute: StudioRouteWithChildren,
  SupportRoute: SupportRoute,
  WelcomeRoute: WelcomeRoute,
  BusinessApplicationsRoute: BusinessApplicationsRoute,
  BusinessApplyRoute: BusinessApplyRoute,
  BusinessCalculatorRoute: BusinessCalculatorRoute,
  CreatorAnalyticsRoute: CreatorAnalyticsRoute,
  CreatorApplicationsRoute: CreatorApplicationsRoute,
  DealsIdRoute: DealsIdRoute,
  ItinerariesIdRoute: ItinerariesIdRoute,
  ItinerariesNewRoute: ItinerariesNewRoute,
  LegalTermsRoute: LegalTermsRoute,
  RCodeRoute: RCodeRoute,
  SoundsIdRoute: SoundsIdRoute,
  UUsernameRoute: UUsernameRoute,
  BusinessIndexRoute: BusinessIndexRoute,
  DealsIndexRoute: DealsIndexRoute,
  DestinationsIndexRoute: DestinationsIndexRoute,
  ItinerariesIndexRoute: ItinerariesIndexRoute,
  LegalIndexRoute: LegalIndexRoute,
  ApiPublicMuxWebhookRoute: ApiPublicMuxWebhookRoute,
  BusinessDealsIdRoute: BusinessDealsIdRouteWithChildren,
  BusinessDealsNewRoute: BusinessDealsNewRoute,
  BusinessInviteTokenRoute: BusinessInviteTokenRoute,
  DestinationsCountryCityRoute: DestinationsCountryCityRoute,
  DestinationsCountryIndexRoute: DestinationsCountryIndexRoute,
  ApiPublicCronDiscoverDealsRoute: ApiPublicCronDiscoverDealsRoute,
  ApiPublicDIdRoute: ApiPublicDIdRoute,
  ApiPublicGoIdRoute: ApiPublicGoIdRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
