/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as SupportRouteImport } from './routes/support'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MapRouteImport } from './routes/map'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InvestRouteImport } from './routes/invest'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as CreateRouteImport } from './routes/create'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudioIndexRouteImport } from './routes/studio.index'
import { Route as LegalIndexRouteImport } from './routes/legal.index'
import { Route as ItinerariesIndexRouteImport } from './routes/itineraries.index'
import { Route as DestinationsIndexRouteImport } from './routes/destinations.index'
import { Route as DealsIndexRouteImport } from './routes/deals.index'
import { Route as BusinessIndexRouteImport } from './routes/business.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as StudioVideosRouteImport } from './routes/studio.videos'
import { Route as StudioThreadsRouteImport } from './routes/studio.threads'
import { Route as StudioScheduleRouteImport } from './routes/studio.schedule'
import { Route as StudioLinksRouteImport } from './routes/studio.links'
import { Route as SoundsIdRouteImport } from './routes/sounds.$id'
import { Route as ReviewBookingIdRouteImport } from './routes/review.$bookingId'
import { Route as RCodeRouteImport } from './routes/r.$code'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalDmcaRouteImport } from './routes/legal.dmca'
import { Route as LegalCreatorAgreementRouteImport } from './routes/legal.creator-agreement'
import { Route as LegalCookiesRouteImport } from './routes/legal.cookies'
import { Route as LegalBusinessAgreementRouteImport } from './routes/legal.business-agreement'
import { Route as ItinerariesNewRouteImport } from './routes/itineraries.new'
import { Route as ItinerariesIdRouteImport } from './routes/itineraries.$id'
import { Route as FeedPlaylistRouteImport } from './routes/feed.playlist'
import { Route as EmailUnsubscribeRouteImport } from './routes/email.unsubscribe'
import { Route as DealsIdRouteImport } from './routes/deals.$id'
import { Route as CreatorEarningsRouteImport } from './routes/creator.earnings'
import { Route as CreatorCalculatorRouteImport } from './routes/creator.calculator'
import { Route as CreatorApplicationsRouteImport } from './routes/creator.applications'
import { Route as CreatorAnalyticsRouteImport } from './routes/creator.analytics'
import { Route as CollectionsIdRouteImport } from './routes/collections.$id'
import { Route as CollabCodeRouteImport } from './routes/collab.$code'
import { Route as BusinessThreadsRouteImport } from './routes/business.threads'
import { Route as BusinessSignupRouteImport } from './routes/business.signup'
import { Route as BusinessRedemptionsRouteImport } from './routes/business.redemptions'
import { Route as BusinessPriceAuditRouteImport } from './routes/business.price-audit'
import { Route as BusinessPhotosRouteImport } from './routes/business.photos'
import { Route as BusinessCollabsRouteImport } from './routes/business.collabs'
import { Route as BusinessCalculatorRouteImport } from './routes/business.calculator'
import { Route as BusinessApplyRouteImport } from './routes/business.apply'
import { Route as BusinessApplicationsRouteImport } from './routes/business.applications'
import { Route as BookReturnRouteImport } from './routes/book.return'
import { Route as BookDealIdRouteImport } from './routes/book.$dealId'
import { Route as AdminVideosRouteImport } from './routes/admin.videos'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSeedRouteImport } from './routes/admin.seed'
import { Route as AdminPayoutsRouteImport } from './routes/admin.payouts'
import { Route as AdminModerationRouteImport } from './routes/admin.moderation'
import { Route as AdminInvestorRouteImport } from './routes/admin.investor'
import { Route as AdminErrorsRouteImport } from './routes/admin.errors'
import { Route as AdminDisputesRouteImport } from './routes/admin.disputes'
import { Route as AdminDiscoveriesRouteImport } from './routes/admin.discoveries'
import { Route as AdminDealsRouteImport } from './routes/admin.deals'
import { Route as AdminConnectRouteImport } from './routes/admin.connect'
import { Route as AccountDeleteRouteImport } from './routes/account.delete'
import { Route as DestinationsCountryIndexRouteImport } from './routes/destinations.$country.index'
import { Route as StudioVideosIdRouteImport } from './routes/studio.videos.$id'
import { Route as StudioThreadsIdRouteImport } from './routes/studio.threads.$id'
import { Route as ReviewBookingIdThanksRouteImport } from './routes/review.$bookingId.thanks'
import { Route as LovableEmailUnsubscribeRouteImport } from './routes/lovable/email/unsubscribe'
import { Route as DestinationsCountryCityRouteImport } from './routes/destinations.$country.$city'
import { Route as BusinessThreadsIdRouteImport } from './routes/business.threads.$id'
import { Route as BusinessOnboardingWebsiteRouteImport } from './routes/business.onboarding.website'
import { Route as BusinessOnboardingPayoutRouteImport } from './routes/business.onboarding.payout'
import { Route as BusinessInviteTokenRouteImport } from './routes/business.invite.$token'
import { Route as BusinessDealsNewRouteImport } from './routes/business.deals.new'
import { Route as BusinessDealsIdRouteImport } from './routes/business.deals.$id'
import { Route as BookMatchCodeRouteImport } from './routes/book.match.$code'
import { Route as ApiPublicMuxWebhookRouteImport } from './routes/api/public/mux-webhook'
import { Route as ApiPublicAttributeRouteImport } from './routes/api/public/attribute'
import { Route as BusinessDealsIdIndexRouteImport } from './routes/business.deals.$id.index'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as BusinessDealsIdEditRouteImport } from './routes/business.deals.$id.edit'
import { Route as BookMatchCodeThanksRouteImport } from './routes/book.match.$code.thanks'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicHooksSyncExternalCalendarsRouteImport } from './routes/api/public/hooks/sync-external-calendars'
import { Route as ApiPublicGoIdRouteImport } from './routes/api/public/go.$id'
import { Route as ApiPublicDIdRouteImport } from './routes/api/public/d.$id'
import { Route as ApiPublicCronSyncYoutubeRouteImport } from './routes/api/public/cron/sync-youtube'
import { Route as ApiPublicCronSyncTiktokRouteImport } from './routes/api/public/cron/sync-tiktok'
import { Route as ApiPublicCronReviewPromptsRouteImport } from './routes/api/public/cron/review-prompts'
import { Route as ApiPublicCronRefreshCreatorTiersRouteImport } from './routes/api/public/cron/refresh-creator-tiers'
import { Route as ApiPublicCronParitySweepRouteImport } from './routes/api/public/cron/parity-sweep'
import { Route as ApiPublicCronFxRefreshRouteImport } from './routes/api/public/cron/fx-refresh'
import { Route as ApiPublicCronExpiringDealsRouteImport } from './routes/api/public/cron/expiring-deals'
import { Route as ApiPublicCronDiscoverDealsRouteImport } from './routes/api/public/cron/discover-deals'
import { Route as ApiPublicCronBusinessDigestRouteImport } from './routes/api/public/cron/business-digest'
import { Route as ApiPublicBIdRouteImport } from './routes/api/public/b.$id'
import { Route as ApiPublicIcalDealDealIdTokenDoticsRouteImport } from './routes/api/public/ical/deal.$dealId.$token[.]ics'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestRoute = InvestRouteImport.update({
  id: '/invest',
  path: '/invest',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioRoute,
} as any)
const LegalIndexRoute = LegalIndexRouteImport.update({
  id: '/legal/',
  path: '/legal/',
  getParentRoute: () => rootRouteImport,
} as any)
const ItinerariesIndexRoute = ItinerariesIndexRouteImport.update({
  id: '/itineraries/',
  path: '/itineraries/',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsIndexRoute = DestinationsIndexRouteImport.update({
  id: '/destinations/',
  path: '/destinations/',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsIndexRoute = DealsIndexRouteImport.update({
  id: '/deals/',
  path: '/deals/',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessIndexRoute = BusinessIndexRouteImport.update({
  id: '/business/',
  path: '/business/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioVideosRoute = StudioVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => StudioRoute,
} as any)
const StudioThreadsRoute = StudioThreadsRouteImport.update({
  id: '/threads',
  path: '/threads',
  getParentRoute: () => StudioRoute,
} as any)
const StudioScheduleRoute = StudioScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => StudioRoute,
} as any)
const StudioLinksRoute = StudioLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => StudioRoute,
} as any)
const SoundsIdRoute = SoundsIdRouteImport.update({
  id: '/sounds/$id',
  path: '/sounds/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewBookingIdRoute = ReviewBookingIdRouteImport.update({
  id: '/review/$bookingId',
  path: '/review/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const RCodeRoute = RCodeRouteImport.update({
  id: '/r/$code',
  path: '/r/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalDmcaRoute = LegalDmcaRouteImport.update({
  id: '/legal/dmca',
  path: '/legal/dmca',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCreatorAgreementRoute = LegalCreatorAgreementRouteImport.update({
  id: '/legal/creator-agreement',
  path: '/legal/creator-agreement',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/legal/cookies',
  path: '/legal/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalBusinessAgreementRoute = LegalBusinessAgreementRouteImport.update({
  id: '/legal/business-agreement',
  path: '/legal/business-agreement',
  getParentRoute: () => rootRouteImport,
} as any)
const ItinerariesNewRoute = ItinerariesNewRouteImport.update({
  id: '/itineraries/new',
  path: '/itineraries/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ItinerariesIdRoute = ItinerariesIdRouteImport.update({
  id: '/itineraries/$id',
  path: '/itineraries/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedPlaylistRoute = FeedPlaylistRouteImport.update({
  id: '/feed/playlist',
  path: '/feed/playlist',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsIdRoute = DealsIdRouteImport.update({
  id: '/deals/$id',
  path: '/deals/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorEarningsRoute = CreatorEarningsRouteImport.update({
  id: '/creator/earnings',
  path: '/creator/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorCalculatorRoute = CreatorCalculatorRouteImport.update({
  id: '/creator/calculator',
  path: '/creator/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorApplicationsRoute = CreatorApplicationsRouteImport.update({
  id: '/creator/applications',
  path: '/creator/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorAnalyticsRoute = CreatorAnalyticsRouteImport.update({
  id: '/creator/analytics',
  path: '/creator/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIdRoute = CollectionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CollectionsRoute,
} as any)
const CollabCodeRoute = CollabCodeRouteImport.update({
  id: '/collab/$code',
  path: '/collab/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessThreadsRoute = BusinessThreadsRouteImport.update({
  id: '/business/threads',
  path: '/business/threads',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessSignupRoute = BusinessSignupRouteImport.update({
  id: '/business/signup',
  path: '/business/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRedemptionsRoute = BusinessRedemptionsRouteImport.update({
  id: '/business/redemptions',
  path: '/business/redemptions',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessPriceAuditRoute = BusinessPriceAuditRouteImport.update({
  id: '/business/price-audit',
  path: '/business/price-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessPhotosRoute = BusinessPhotosRouteImport.update({
  id: '/business/photos',
  path: '/business/photos',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessCollabsRoute = BusinessCollabsRouteImport.update({
  id: '/business/collabs',
  path: '/business/collabs',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessCalculatorRoute = BusinessCalculatorRouteImport.update({
  id: '/business/calculator',
  path: '/business/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessApplyRoute = BusinessApplyRouteImport.update({
  id: '/business/apply',
  path: '/business/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessApplicationsRoute = BusinessApplicationsRouteImport.update({
  id: '/business/applications',
  path: '/business/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const BookReturnRoute = BookReturnRouteImport.update({
  id: '/book/return',
  path: '/book/return',
  getParentRoute: () => rootRouteImport,
} as any)
const BookDealIdRoute = BookDealIdRouteImport.update({
  id: '/book/$dealId',
  path: '/book/$dealId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVideosRoute = AdminVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeedRoute = AdminSeedRouteImport.update({
  id: '/seed',
  path: '/seed',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPayoutsRoute = AdminPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModerationRoute = AdminModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInvestorRoute = AdminInvestorRouteImport.update({
  id: '/investor',
  path: '/investor',
  getParentRoute: () => AdminRoute,
} as any)
const AdminErrorsRoute = AdminErrorsRouteImport.update({
  id: '/errors',
  path: '/errors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDisputesRoute = AdminDisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDiscoveriesRoute = AdminDiscoveriesRouteImport.update({
  id: '/discoveries',
  path: '/discoveries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDealsRoute = AdminDealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConnectRoute = AdminConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => AdminRoute,
} as any)
const AccountDeleteRoute = AccountDeleteRouteImport.update({
  id: '/account/delete',
  path: '/account/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsCountryIndexRoute =
  DestinationsCountryIndexRouteImport.update({
    id: '/destinations/$country/',
    path: '/destinations/$country/',
    getParentRoute: () => rootRouteImport,
  } as any)
const StudioVideosIdRoute = StudioVideosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StudioVideosRoute,
} as any)
const StudioThreadsIdRoute = StudioThreadsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StudioThreadsRoute,
} as any)
const ReviewBookingIdThanksRoute = ReviewBookingIdThanksRouteImport.update({
  id: '/thanks',
  path: '/thanks',
  getParentRoute: () => ReviewBookingIdRoute,
} as any)
const LovableEmailUnsubscribeRoute = LovableEmailUnsubscribeRouteImport.update({
  id: '/lovable/email/unsubscribe',
  path: '/lovable/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsCountryCityRoute = DestinationsCountryCityRouteImport.update({
  id: '/destinations/$country/$city',
  path: '/destinations/$country/$city',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessThreadsIdRoute = BusinessThreadsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BusinessThreadsRoute,
} as any)
const BusinessOnboardingWebsiteRoute =
  BusinessOnboardingWebsiteRouteImport.update({
    id: '/business/onboarding/website',
    path: '/business/onboarding/website',
    getParentRoute: () => rootRouteImport,
  } as any)
const BusinessOnboardingPayoutRoute =
  BusinessOnboardingPayoutRouteImport.update({
    id: '/business/onboarding/payout',
    path: '/business/onboarding/payout',
    getParentRoute: () => rootRouteImport,
  } as any)
const BusinessInviteTokenRoute = BusinessInviteTokenRouteImport.update({
  id: '/business/invite/$token',
  path: '/business/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessDealsNewRoute = BusinessDealsNewRouteImport.update({
  id: '/business/deals/new',
  path: '/business/deals/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessDealsIdRoute = BusinessDealsIdRouteImport.update({
  id: '/business/deals/$id',
  path: '/business/deals/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BookMatchCodeRoute = BookMatchCodeRouteImport.update({
  id: '/book/match/$code',
  path: '/book/match/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMuxWebhookRoute = ApiPublicMuxWebhookRouteImport.update({
  id: '/api/public/mux-webhook',
  path: '/api/public/mux-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAttributeRoute = ApiPublicAttributeRouteImport.update({
  id: '/api/public/attribute',
  path: '/api/public/attribute',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessDealsIdIndexRoute = BusinessDealsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BusinessDealsIdRoute,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessDealsIdEditRoute = BusinessDealsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => BusinessDealsIdRoute,
} as any)
const BookMatchCodeThanksRoute = BookMatchCodeThanksRouteImport.update({
  id: '/thanks',
  path: '/thanks',
  getParentRoute: () => BookMatchCodeRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSyncExternalCalendarsRoute =
  ApiPublicHooksSyncExternalCalendarsRouteImport.update({
    id: '/api/public/hooks/sync-external-calendars',
    path: '/api/public/hooks/sync-external-calendars',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGoIdRoute = ApiPublicGoIdRouteImport.update({
  id: '/api/public/go/$id',
  path: '/api/public/go/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDIdRoute = ApiPublicDIdRouteImport.update({
  id: '/api/public/d/$id',
  path: '/api/public/d/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronSyncYoutubeRoute =
  ApiPublicCronSyncYoutubeRouteImport.update({
    id: '/api/public/cron/sync-youtube',
    path: '/api/public/cron/sync-youtube',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronSyncTiktokRoute = ApiPublicCronSyncTiktokRouteImport.update({
  id: '/api/public/cron/sync-tiktok',
  path: '/api/public/cron/sync-tiktok',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronReviewPromptsRoute =
  ApiPublicCronReviewPromptsRouteImport.update({
    id: '/api/public/cron/review-prompts',
    path: '/api/public/cron/review-prompts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronRefreshCreatorTiersRoute =
  ApiPublicCronRefreshCreatorTiersRouteImport.update({
    id: '/api/public/cron/refresh-creator-tiers',
    path: '/api/public/cron/refresh-creator-tiers',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronParitySweepRoute =
  ApiPublicCronParitySweepRouteImport.update({
    id: '/api/public/cron/parity-sweep',
    path: '/api/public/cron/parity-sweep',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronFxRefreshRoute = ApiPublicCronFxRefreshRouteImport.update({
  id: '/api/public/cron/fx-refresh',
  path: '/api/public/cron/fx-refresh',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronExpiringDealsRoute =
  ApiPublicCronExpiringDealsRouteImport.update({
    id: '/api/public/cron/expiring-deals',
    path: '/api/public/cron/expiring-deals',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronDiscoverDealsRoute =
  ApiPublicCronDiscoverDealsRouteImport.update({
    id: '/api/public/cron/discover-deals',
    path: '/api/public/cron/discover-deals',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronBusinessDigestRoute =
  ApiPublicCronBusinessDigestRouteImport.update({
    id: '/api/public/cron/business-digest',
    path: '/api/public/cron/business-digest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBIdRoute = ApiPublicBIdRouteImport.update({
  id: '/api/public/b/$id',
  path: '/api/public/b/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIcalDealDealIdTokenDoticsRoute =
  ApiPublicIcalDealDealIdTokenDoticsRouteImport.update({
    id: '/api/public/ical/deal/$dealId/$token.ics',
    path: '/api/public/ical/deal/$dealId/$token.ics',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/collections': typeof CollectionsRouteWithChildren
  '/create': typeof CreateRoute
  '/download': typeof DownloadRoute
  '/invest': typeof InvestRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRouteWithChildren
  '/support': typeof SupportRoute
  '/welcome': typeof WelcomeRoute
  '/account/delete': typeof AccountDeleteRoute
  '/admin/connect': typeof AdminConnectRoute
  '/admin/deals': typeof AdminDealsRoute
  '/admin/discoveries': typeof AdminDiscoveriesRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/errors': typeof AdminErrorsRoute
  '/admin/investor': typeof AdminInvestorRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/seed': typeof AdminSeedRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/videos': typeof AdminVideosRoute
  '/book/$dealId': typeof BookDealIdRoute
  '/book/return': typeof BookReturnRoute
  '/business/applications': typeof BusinessApplicationsRoute
  '/business/apply': typeof BusinessApplyRoute
  '/business/calculator': typeof BusinessCalculatorRoute
  '/business/collabs': typeof BusinessCollabsRoute
  '/business/photos': typeof BusinessPhotosRoute
  '/business/price-audit': typeof BusinessPriceAuditRoute
  '/business/redemptions': typeof BusinessRedemptionsRoute
  '/business/signup': typeof BusinessSignupRoute
  '/business/threads': typeof BusinessThreadsRouteWithChildren
  '/collab/$code': typeof CollabCodeRoute
  '/collections/$id': typeof CollectionsIdRoute
  '/creator/analytics': typeof CreatorAnalyticsRoute
  '/creator/applications': typeof CreatorApplicationsRoute
  '/creator/calculator': typeof CreatorCalculatorRoute
  '/creator/earnings': typeof CreatorEarningsRoute
  '/deals/$id': typeof DealsIdRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/feed/playlist': typeof FeedPlaylistRoute
  '/itineraries/$id': typeof ItinerariesIdRoute
  '/itineraries/new': typeof ItinerariesNewRoute
  '/legal/business-agreement': typeof LegalBusinessAgreementRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/creator-agreement': typeof LegalCreatorAgreementRoute
  '/legal/dmca': typeof LegalDmcaRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/r/$code': typeof RCodeRoute
  '/review/$bookingId': typeof ReviewBookingIdRouteWithChildren
  '/sounds/$id': typeof SoundsIdRoute
  '/studio/links': typeof StudioLinksRoute
  '/studio/schedule': typeof StudioScheduleRoute
  '/studio/threads': typeof StudioThreadsRouteWithChildren
  '/studio/videos': typeof StudioVideosRouteWithChildren
  '/u/$username': typeof UUsernameRoute
  '/admin/': typeof AdminIndexRoute
  '/business/': typeof BusinessIndexRoute
  '/deals/': typeof DealsIndexRoute
  '/destinations/': typeof DestinationsIndexRoute
  '/itineraries/': typeof ItinerariesIndexRoute
  '/legal/': typeof LegalIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/api/public/attribute': typeof ApiPublicAttributeRoute
  '/api/public/mux-webhook': typeof ApiPublicMuxWebhookRoute
  '/book/match/$code': typeof BookMatchCodeRouteWithChildren
  '/business/deals/$id': typeof BusinessDealsIdRouteWithChildren
  '/business/deals/new': typeof BusinessDealsNewRoute
  '/business/invite/$token': typeof BusinessInviteTokenRoute
  '/business/onboarding/payout': typeof BusinessOnboardingPayoutRoute
  '/business/onboarding/website': typeof BusinessOnboardingWebsiteRoute
  '/business/threads/$id': typeof BusinessThreadsIdRoute
  '/destinations/$country/$city': typeof DestinationsCountryCityRoute
  '/lovable/email/unsubscribe': typeof LovableEmailUnsubscribeRoute
  '/review/$bookingId/thanks': typeof ReviewBookingIdThanksRoute
  '/studio/threads/$id': typeof StudioThreadsIdRoute
  '/studio/videos/$id': typeof StudioVideosIdRoute
  '/destinations/$country/': typeof DestinationsCountryIndexRoute
  '/api/public/b/$id': typeof ApiPublicBIdRoute
  '/api/public/cron/business-digest': typeof ApiPublicCronBusinessDigestRoute
  '/api/public/cron/discover-deals': typeof ApiPublicCronDiscoverDealsRoute
  '/api/public/cron/expiring-deals': typeof ApiPublicCronExpiringDealsRoute
  '/api/public/cron/fx-refresh': typeof ApiPublicCronFxRefreshRoute
  '/api/public/cron/parity-sweep': typeof ApiPublicCronParitySweepRoute
  '/api/public/cron/refresh-creator-tiers': typeof ApiPublicCronRefreshCreatorTiersRoute
  '/api/public/cron/review-prompts': typeof ApiPublicCronReviewPromptsRoute
  '/api/public/cron/sync-tiktok': typeof ApiPublicCronSyncTiktokRoute
  '/api/public/cron/sync-youtube': typeof ApiPublicCronSyncYoutubeRoute
  '/api/public/d/$id': typeof ApiPublicDIdRoute
  '/api/public/go/$id': typeof ApiPublicGoIdRoute
  '/api/public/hooks/sync-external-calendars': typeof ApiPublicHooksSyncExternalCalendarsRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/book/match/$code/thanks': typeof BookMatchCodeThanksRoute
  '/business/deals/$id/edit': typeof BusinessDealsIdEditRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/business/deals/$id/': typeof BusinessDealsIdIndexRoute
  '/api/public/ical/deal/$dealId/$token.ics': typeof ApiPublicIcalDealDealIdTokenDoticsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/create': typeof CreateRoute
  '/download': typeof DownloadRoute
  '/invest': typeof InvestRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/welcome': typeof WelcomeRoute
  '/account/delete': typeof AccountDeleteRoute
  '/admin/connect': typeof AdminConnectRoute
  '/admin/deals': typeof AdminDealsRoute
  '/admin/discoveries': typeof AdminDiscoveriesRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/errors': typeof AdminErrorsRoute
  '/admin/investor': typeof AdminInvestorRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/seed': typeof AdminSeedRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/videos': typeof AdminVideosRoute
  '/book/$dealId': typeof BookDealIdRoute
  '/book/return': typeof BookReturnRoute
  '/business/applications': typeof BusinessApplicationsRoute
  '/business/apply': typeof BusinessApplyRoute
  '/business/calculator': typeof BusinessCalculatorRoute
  '/business/collabs': typeof BusinessCollabsRoute
  '/business/photos': typeof BusinessPhotosRoute
  '/business/price-audit': typeof BusinessPriceAuditRoute
  '/business/redemptions': typeof BusinessRedemptionsRoute
  '/business/signup': typeof BusinessSignupRoute
  '/business/threads': typeof BusinessThreadsRouteWithChildren
  '/collab/$code': typeof CollabCodeRoute
  '/collections/$id': typeof CollectionsIdRoute
  '/creator/analytics': typeof CreatorAnalyticsRoute
  '/creator/applications': typeof CreatorApplicationsRoute
  '/creator/calculator': typeof CreatorCalculatorRoute
  '/creator/earnings': typeof CreatorEarningsRoute
  '/deals/$id': typeof DealsIdRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/feed/playlist': typeof FeedPlaylistRoute
  '/itineraries/$id': typeof ItinerariesIdRoute
  '/itineraries/new': typeof ItinerariesNewRoute
  '/legal/business-agreement': typeof LegalBusinessAgreementRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/creator-agreement': typeof LegalCreatorAgreementRoute
  '/legal/dmca': typeof LegalDmcaRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/r/$code': typeof RCodeRoute
  '/review/$bookingId': typeof ReviewBookingIdRouteWithChildren
  '/sounds/$id': typeof SoundsIdRoute
  '/studio/links': typeof StudioLinksRoute
  '/studio/schedule': typeof StudioScheduleRoute
  '/studio/threads': typeof StudioThreadsRouteWithChildren
  '/studio/videos': typeof StudioVideosRouteWithChildren
  '/u/$username': typeof UUsernameRoute
  '/admin': typeof AdminIndexRoute
  '/business': typeof BusinessIndexRoute
  '/deals': typeof DealsIndexRoute
  '/destinations': typeof DestinationsIndexRoute
  '/itineraries': typeof ItinerariesIndexRoute
  '/legal': typeof LegalIndexRoute
  '/studio': typeof StudioIndexRoute
  '/api/public/attribute': typeof ApiPublicAttributeRoute
  '/api/public/mux-webhook': typeof ApiPublicMuxWebhookRoute
  '/book/match/$code': typeof BookMatchCodeRouteWithChildren
  '/business/deals/new': typeof BusinessDealsNewRoute
  '/business/invite/$token': typeof BusinessInviteTokenRoute
  '/business/onboarding/payout': typeof BusinessOnboardingPayoutRoute
  '/business/onboarding/website': typeof BusinessOnboardingWebsiteRoute
  '/business/threads/$id': typeof BusinessThreadsIdRoute
  '/destinations/$country/$city': typeof DestinationsCountryCityRoute
  '/lovable/email/unsubscribe': typeof LovableEmailUnsubscribeRoute
  '/review/$bookingId/thanks': typeof ReviewBookingIdThanksRoute
  '/studio/threads/$id': typeof StudioThreadsIdRoute
  '/studio/videos/$id': typeof StudioVideosIdRoute
  '/destinations/$country': typeof DestinationsCountryIndexRoute
  '/api/public/b/$id': typeof ApiPublicBIdRoute
  '/api/public/cron/business-digest': typeof ApiPublicCronBusinessDigestRoute
  '/api/public/cron/discover-deals': typeof ApiPublicCronDiscoverDealsRoute
  '/api/public/cron/expiring-deals': typeof ApiPublicCronExpiringDealsRoute
  '/api/public/cron/fx-refresh': typeof ApiPublicCronFxRefreshRoute
  '/api/public/cron/parity-sweep': typeof ApiPublicCronParitySweepRoute
  '/api/public/cron/refresh-creator-tiers': typeof ApiPublicCronRefreshCreatorTiersRoute
  '/api/public/cron/review-prompts': typeof ApiPublicCronReviewPromptsRoute
  '/api/public/cron/sync-tiktok': typeof ApiPublicCronSyncTiktokRoute
  '/api/public/cron/sync-youtube': typeof ApiPublicCronSyncYoutubeRoute
  '/api/public/d/$id': typeof ApiPublicDIdRoute
  '/api/public/go/$id': typeof ApiPublicGoIdRoute
  '/api/public/hooks/sync-external-calendars': typeof ApiPublicHooksSyncExternalCalendarsRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/book/match/$code/thanks': typeof BookMatchCodeThanksRoute
  '/business/deals/$id/edit': typeof BusinessDealsIdEditRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/business/deals/$id': typeof BusinessDealsIdIndexRoute
  '/api/public/ical/deal/$dealId/$token.ics': typeof ApiPublicIcalDealDealIdTokenDoticsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/collections': typeof CollectionsRouteWithChildren
  '/create': typeof CreateRoute
  '/download': typeof DownloadRoute
  '/invest': typeof InvestRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRouteWithChildren
  '/support': typeof SupportRoute
  '/welcome': typeof WelcomeRoute
  '/account/delete': typeof AccountDeleteRoute
  '/admin/connect': typeof AdminConnectRoute
  '/admin/deals': typeof AdminDealsRoute
  '/admin/discoveries': typeof AdminDiscoveriesRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/errors': typeof AdminErrorsRoute
  '/admin/investor': typeof AdminInvestorRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/seed': typeof AdminSeedRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/videos': typeof AdminVideosRoute
  '/book/$dealId': typeof BookDealIdRoute
  '/book/return': typeof BookReturnRoute
  '/business/applications': typeof BusinessApplicationsRoute
  '/business/apply': typeof BusinessApplyRoute
  '/business/calculator': typeof BusinessCalculatorRoute
  '/business/collabs': typeof BusinessCollabsRoute
  '/business/photos': typeof BusinessPhotosRoute
  '/business/price-audit': typeof BusinessPriceAuditRoute
  '/business/redemptions': typeof BusinessRedemptionsRoute
  '/business/signup': typeof BusinessSignupRoute
  '/business/threads': typeof BusinessThreadsRouteWithChildren
  '/collab/$code': typeof CollabCodeRoute
  '/collections/$id': typeof CollectionsIdRoute
  '/creator/analytics': typeof CreatorAnalyticsRoute
  '/creator/applications': typeof CreatorApplicationsRoute
  '/creator/calculator': typeof CreatorCalculatorRoute
  '/creator/earnings': typeof CreatorEarningsRoute
  '/deals/$id': typeof DealsIdRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/feed/playlist': typeof FeedPlaylistRoute
  '/itineraries/$id': typeof ItinerariesIdRoute
  '/itineraries/new': typeof ItinerariesNewRoute
  '/legal/business-agreement': typeof LegalBusinessAgreementRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/creator-agreement': typeof LegalCreatorAgreementRoute
  '/legal/dmca': typeof LegalDmcaRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/r/$code': typeof RCodeRoute
  '/review/$bookingId': typeof ReviewBookingIdRouteWithChildren
  '/sounds/$id': typeof SoundsIdRoute
  '/studio/links': typeof StudioLinksRoute
  '/studio/schedule': typeof StudioScheduleRoute
  '/studio/threads': typeof StudioThreadsRouteWithChildren
  '/studio/videos': typeof StudioVideosRouteWithChildren
  '/u/$username': typeof UUsernameRoute
  '/admin/': typeof AdminIndexRoute
  '/business/': typeof BusinessIndexRoute
  '/deals/': typeof DealsIndexRoute
  '/destinations/': typeof DestinationsIndexRoute
  '/itineraries/': typeof ItinerariesIndexRoute
  '/legal/': typeof LegalIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/api/public/attribute': typeof ApiPublicAttributeRoute
  '/api/public/mux-webhook': typeof ApiPublicMuxWebhookRoute
  '/book/match/$code': typeof BookMatchCodeRouteWithChildren
  '/business/deals/$id': typeof BusinessDealsIdRouteWithChildren
  '/business/deals/new': typeof BusinessDealsNewRoute
  '/business/invite/$token': typeof BusinessInviteTokenRoute
  '/business/onboarding/payout': typeof BusinessOnboardingPayoutRoute
  '/business/onboarding/website': typeof BusinessOnboardingWebsiteRoute
  '/business/threads/$id': typeof BusinessThreadsIdRoute
  '/destinations/$country/$city': typeof DestinationsCountryCityRoute
  '/lovable/email/unsubscribe': typeof LovableEmailUnsubscribeRoute
  '/review/$bookingId/thanks': typeof ReviewBookingIdThanksRoute
  '/studio/threads/$id': typeof StudioThreadsIdRoute
  '/studio/videos/$id': typeof StudioVideosIdRoute
  '/destinations/$country/': typeof DestinationsCountryIndexRoute
  '/api/public/b/$id': typeof ApiPublicBIdRoute
  '/api/public/cron/business-digest': typeof ApiPublicCronBusinessDigestRoute
  '/api/public/cron/discover-deals': typeof ApiPublicCronDiscoverDealsRoute
  '/api/public/cron/expiring-deals': typeof ApiPublicCronExpiringDealsRoute
  '/api/public/cron/fx-refresh': typeof ApiPublicCronFxRefreshRoute
  '/api/public/cron/parity-sweep': typeof ApiPublicCronParitySweepRoute
  '/api/public/cron/refresh-creator-tiers': typeof ApiPublicCronRefreshCreatorTiersRoute
  '/api/public/cron/review-prompts': typeof ApiPublicCronReviewPromptsRoute
  '/api/public/cron/sync-tiktok': typeof ApiPublicCronSyncTiktokRoute
  '/api/public/cron/sync-youtube': typeof ApiPublicCronSyncYoutubeRoute
  '/api/public/d/$id': typeof ApiPublicDIdRoute
  '/api/public/go/$id': typeof ApiPublicGoIdRoute
  '/api/public/hooks/sync-external-calendars': typeof ApiPublicHooksSyncExternalCalendarsRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/book/match/$code/thanks': typeof BookMatchCodeThanksRoute
  '/business/deals/$id/edit': typeof BusinessDealsIdEditRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/business/deals/$id/': typeof BusinessDealsIdIndexRoute
  '/api/public/ical/deal/$dealId/$token.ics': typeof ApiPublicIcalDealDealIdTokenDoticsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/collections'
    | '/create'
    | '/download'
    | '/invest'
    | '/login'
    | '/map'
    | '/notifications'
    | '/profile'
    | '/reset-password'
    | '/robots.txt'
    | '/search'
    | '/settings'
    | '/sitemap.xml'
    | '/studio'
    | '/support'
    | '/welcome'
    | '/account/delete'
    | '/admin/connect'
    | '/admin/deals'
    | '/admin/discoveries'
    | '/admin/disputes'
    | '/admin/errors'
    | '/admin/investor'
    | '/admin/moderation'
    | '/admin/payouts'
    | '/admin/seed'
    | '/admin/users'
    | '/admin/videos'
    | '/book/$dealId'
    | '/book/return'
    | '/business/applications'
    | '/business/apply'
    | '/business/calculator'
    | '/business/collabs'
    | '/business/photos'
    | '/business/price-audit'
    | '/business/redemptions'
    | '/business/signup'
    | '/business/threads'
    | '/collab/$code'
    | '/collections/$id'
    | '/creator/analytics'
    | '/creator/applications'
    | '/creator/calculator'
    | '/creator/earnings'
    | '/deals/$id'
    | '/email/unsubscribe'
    | '/feed/playlist'
    | '/itineraries/$id'
    | '/itineraries/new'
    | '/legal/business-agreement'
    | '/legal/cookies'
    | '/legal/creator-agreement'
    | '/legal/dmca'
    | '/legal/privacy'
    | '/legal/terms'
    | '/r/$code'
    | '/review/$bookingId'
    | '/sounds/$id'
    | '/studio/links'
    | '/studio/schedule'
    | '/studio/threads'
    | '/studio/videos'
    | '/u/$username'
    | '/admin/'
    | '/business/'
    | '/deals/'
    | '/destinations/'
    | '/itineraries/'
    | '/legal/'
    | '/studio/'
    | '/api/public/attribute'
    | '/api/public/mux-webhook'
    | '/book/match/$code'
    | '/business/deals/$id'
    | '/business/deals/new'
    | '/business/invite/$token'
    | '/business/onboarding/payout'
    | '/business/onboarding/website'
    | '/business/threads/$id'
    | '/destinations/$country/$city'
    | '/lovable/email/unsubscribe'
    | '/review/$bookingId/thanks'
    | '/studio/threads/$id'
    | '/studio/videos/$id'
    | '/destinations/$country/'
    | '/api/public/b/$id'
    | '/api/public/cron/business-digest'
    | '/api/public/cron/discover-deals'
    | '/api/public/cron/expiring-deals'
    | '/api/public/cron/fx-refresh'
    | '/api/public/cron/parity-sweep'
    | '/api/public/cron/refresh-creator-tiers'
    | '/api/public/cron/review-prompts'
    | '/api/public/cron/sync-tiktok'
    | '/api/public/cron/sync-youtube'
    | '/api/public/d/$id'
    | '/api/public/go/$id'
    | '/api/public/hooks/sync-external-calendars'
    | '/api/public/payments/webhook'
    | '/book/match/$code/thanks'
    | '/business/deals/$id/edit'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/business/deals/$id/'
    | '/api/public/ical/deal/$dealId/$token.ics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/collections'
    | '/create'
    | '/download'
    | '/invest'
    | '/login'
    | '/map'
    | '/notifications'
    | '/profile'
    | '/reset-password'
    | '/robots.txt'
    | '/search'
    | '/settings'
    | '/sitemap.xml'
    | '/support'
    | '/welcome'
    | '/account/delete'
    | '/admin/connect'
    | '/admin/deals'
    | '/admin/discoveries'
    | '/admin/disputes'
    | '/admin/errors'
    | '/admin/investor'
    | '/admin/moderation'
    | '/admin/payouts'
    | '/admin/seed'
    | '/admin/users'
    | '/admin/videos'
    | '/book/$dealId'
    | '/book/return'
    | '/business/applications'
    | '/business/apply'
    | '/business/calculator'
    | '/business/collabs'
    | '/business/photos'
    | '/business/price-audit'
    | '/business/redemptions'
    | '/business/signup'
    | '/business/threads'
    | '/collab/$code'
    | '/collections/$id'
    | '/creator/analytics'
    | '/creator/applications'
    | '/creator/calculator'
    | '/creator/earnings'
    | '/deals/$id'
    | '/email/unsubscribe'
    | '/feed/playlist'
    | '/itineraries/$id'
    | '/itineraries/new'
    | '/legal/business-agreement'
    | '/legal/cookies'
    | '/legal/creator-agreement'
    | '/legal/dmca'
    | '/legal/privacy'
    | '/legal/terms'
    | '/r/$code'
    | '/review/$bookingId'
    | '/sounds/$id'
    | '/studio/links'
    | '/studio/schedule'
    | '/studio/threads'
    | '/studio/videos'
    | '/u/$username'
    | '/admin'
    | '/business'
    | '/deals'
    | '/destinations'
    | '/itineraries'
    | '/legal'
    | '/studio'
    | '/api/public/attribute'
    | '/api/public/mux-webhook'
    | '/book/match/$code'
    | '/business/deals/new'
    | '/business/invite/$token'
    | '/business/onboarding/payout'
    | '/business/onboarding/website'
    | '/business/threads/$id'
    | '/destinations/$country/$city'
    | '/lovable/email/unsubscribe'
    | '/review/$bookingId/thanks'
    | '/studio/threads/$id'
    | '/studio/videos/$id'
    | '/destinations/$country'
    | '/api/public/b/$id'
    | '/api/public/cron/business-digest'
    | '/api/public/cron/discover-deals'
    | '/api/public/cron/expiring-deals'
    | '/api/public/cron/fx-refresh'
    | '/api/public/cron/parity-sweep'
    | '/api/public/cron/refresh-creator-tiers'
    | '/api/public/cron/review-prompts'
    | '/api/public/cron/sync-tiktok'
    | '/api/public/cron/sync-youtube'
    | '/api/public/d/$id'
    | '/api/public/go/$id'
    | '/api/public/hooks/sync-external-calendars'
    | '/api/public/payments/webhook'
    | '/book/match/$code/thanks'
    | '/business/deals/$id/edit'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/business/deals/$id'
    | '/api/public/ical/deal/$dealId/$token.ics'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/collections'
    | '/create'
    | '/download'
    | '/invest'
    | '/login'
    | '/map'
    | '/notifications'
    | '/profile'
    | '/reset-password'
    | '/robots.txt'
    | '/search'
    | '/settings'
    | '/sitemap.xml'
    | '/studio'
    | '/support'
    | '/welcome'
    | '/account/delete'
    | '/admin/connect'
    | '/admin/deals'
    | '/admin/discoveries'
    | '/admin/disputes'
    | '/admin/errors'
    | '/admin/investor'
    | '/admin/moderation'
    | '/admin/payouts'
    | '/admin/seed'
    | '/admin/users'
    | '/admin/videos'
    | '/book/$dealId'
    | '/book/return'
    | '/business/applications'
    | '/business/apply'
    | '/business/calculator'
    | '/business/collabs'
    | '/business/photos'
    | '/business/price-audit'
    | '/business/redemptions'
    | '/business/signup'
    | '/business/threads'
    | '/collab/$code'
    | '/collections/$id'
    | '/creator/analytics'
    | '/creator/applications'
    | '/creator/calculator'
    | '/creator/earnings'
    | '/deals/$id'
    | '/email/unsubscribe'
    | '/feed/playlist'
    | '/itineraries/$id'
    | '/itineraries/new'
    | '/legal/business-agreement'
    | '/legal/cookies'
    | '/legal/creator-agreement'
    | '/legal/dmca'
    | '/legal/privacy'
    | '/legal/terms'
    | '/r/$code'
    | '/review/$bookingId'
    | '/sounds/$id'
    | '/studio/links'
    | '/studio/schedule'
    | '/studio/threads'
    | '/studio/videos'
    | '/u/$username'
    | '/admin/'
    | '/business/'
    | '/deals/'
    | '/destinations/'
    | '/itineraries/'
    | '/legal/'
    | '/studio/'
    | '/api/public/attribute'
    | '/api/public/mux-webhook'
    | '/book/match/$code'
    | '/business/deals/$id'
    | '/business/deals/new'
    | '/business/invite/$token'
    | '/business/onboarding/payout'
    | '/business/onboarding/website'
    | '/business/threads/$id'
    | '/destinations/$country/$city'
    | '/lovable/email/unsubscribe'
    | '/review/$bookingId/thanks'
    | '/studio/threads/$id'
    | '/studio/videos/$id'
    | '/destinations/$country/'
    | '/api/public/b/$id'
    | '/api/public/cron/business-digest'
    | '/api/public/cron/discover-deals'
    | '/api/public/cron/expiring-deals'
    | '/api/public/cron/fx-refresh'
    | '/api/public/cron/parity-sweep'
    | '/api/public/cron/refresh-creator-tiers'
    | '/api/public/cron/review-prompts'
    | '/api/public/cron/sync-tiktok'
    | '/api/public/cron/sync-youtube'
    | '/api/public/d/$id'
    | '/api/public/go/$id'
    | '/api/public/hooks/sync-external-calendars'
    | '/api/public/payments/webhook'
    | '/book/match/$code/thanks'
    | '/business/deals/$id/edit'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/business/deals/$id/'
    | '/api/public/ical/deal/$dealId/$token.ics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CollectionsRoute: typeof CollectionsRouteWithChildren
  CreateRoute: typeof CreateRoute
  DownloadRoute: typeof DownloadRoute
  InvestRoute: typeof InvestRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StudioRoute: typeof StudioRouteWithChildren
  SupportRoute: typeof SupportRoute
  WelcomeRoute: typeof WelcomeRoute
  AccountDeleteRoute: typeof AccountDeleteRoute
  BookDealIdRoute: typeof BookDealIdRoute
  BookReturnRoute: typeof BookReturnRoute
  BusinessApplicationsRoute: typeof BusinessApplicationsRoute
  BusinessApplyRoute: typeof BusinessApplyRoute
  BusinessCalculatorRoute: typeof BusinessCalculatorRoute
  BusinessCollabsRoute: typeof BusinessCollabsRoute
  BusinessPhotosRoute: typeof BusinessPhotosRoute
  BusinessPriceAuditRoute: typeof BusinessPriceAuditRoute
  BusinessRedemptionsRoute: typeof BusinessRedemptionsRoute
  BusinessSignupRoute: typeof BusinessSignupRoute
  BusinessThreadsRoute: typeof BusinessThreadsRouteWithChildren
  CollabCodeRoute: typeof CollabCodeRoute
  CreatorAnalyticsRoute: typeof CreatorAnalyticsRoute
  CreatorApplicationsRoute: typeof CreatorApplicationsRoute
  CreatorCalculatorRoute: typeof CreatorCalculatorRoute
  CreatorEarningsRoute: typeof CreatorEarningsRoute
  DealsIdRoute: typeof DealsIdRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  FeedPlaylistRoute: typeof FeedPlaylistRoute
  ItinerariesIdRoute: typeof ItinerariesIdRoute
  ItinerariesNewRoute: typeof ItinerariesNewRoute
  LegalBusinessAgreementRoute: typeof LegalBusinessAgreementRoute
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalCreatorAgreementRoute: typeof LegalCreatorAgreementRoute
  LegalDmcaRoute: typeof LegalDmcaRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  RCodeRoute: typeof RCodeRoute
  ReviewBookingIdRoute: typeof ReviewBookingIdRouteWithChildren
  SoundsIdRoute: typeof SoundsIdRoute
  UUsernameRoute: typeof UUsernameRoute
  BusinessIndexRoute: typeof BusinessIndexRoute
  DealsIndexRoute: typeof DealsIndexRoute
  DestinationsIndexRoute: typeof DestinationsIndexRoute
  ItinerariesIndexRoute: typeof ItinerariesIndexRoute
  LegalIndexRoute: typeof LegalIndexRoute
  ApiPublicAttributeRoute: typeof ApiPublicAttributeRoute
  ApiPublicMuxWebhookRoute: typeof ApiPublicMuxWebhookRoute
  BookMatchCodeRoute: typeof BookMatchCodeRouteWithChildren
  BusinessDealsIdRoute: typeof BusinessDealsIdRouteWithChildren
  BusinessDealsNewRoute: typeof BusinessDealsNewRoute
  BusinessInviteTokenRoute: typeof BusinessInviteTokenRoute
  BusinessOnboardingPayoutRoute: typeof BusinessOnboardingPayoutRoute
  BusinessOnboardingWebsiteRoute: typeof BusinessOnboardingWebsiteRoute
  DestinationsCountryCityRoute: typeof DestinationsCountryCityRoute
  LovableEmailUnsubscribeRoute: typeof LovableEmailUnsubscribeRoute
  DestinationsCountryIndexRoute: typeof DestinationsCountryIndexRoute
  ApiPublicBIdRoute: typeof ApiPublicBIdRoute
  ApiPublicCronBusinessDigestRoute: typeof ApiPublicCronBusinessDigestRoute
  ApiPublicCronDiscoverDealsRoute: typeof ApiPublicCronDiscoverDealsRoute
  ApiPublicCronExpiringDealsRoute: typeof ApiPublicCronExpiringDealsRoute
  ApiPublicCronFxRefreshRoute: typeof ApiPublicCronFxRefreshRoute
  ApiPublicCronParitySweepRoute: typeof ApiPublicCronParitySweepRoute
  ApiPublicCronRefreshCreatorTiersRoute: typeof ApiPublicCronRefreshCreatorTiersRoute
  ApiPublicCronReviewPromptsRoute: typeof ApiPublicCronReviewPromptsRoute
  ApiPublicCronSyncTiktokRoute: typeof ApiPublicCronSyncTiktokRoute
  ApiPublicCronSyncYoutubeRoute: typeof ApiPublicCronSyncYoutubeRoute
  ApiPublicDIdRoute: typeof ApiPublicDIdRoute
  ApiPublicGoIdRoute: typeof ApiPublicGoIdRoute
  ApiPublicHooksSyncExternalCalendarsRoute: typeof ApiPublicHooksSyncExternalCalendarsRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  ApiPublicIcalDealDealIdTokenDoticsRoute: typeof ApiPublicIcalDealDealIdTokenDoticsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invest': {
      id: '/invest'
      path: '/invest'
      fullPath: '/invest'
      preLoaderRoute: typeof InvestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof StudioRoute
    }
    '/legal/': {
      id: '/legal/'
      path: '/legal'
      fullPath: '/legal/'
      preLoaderRoute: typeof LegalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itineraries/': {
      id: '/itineraries/'
      path: '/itineraries'
      fullPath: '/itineraries/'
      preLoaderRoute: typeof ItinerariesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/': {
      id: '/destinations/'
      path: '/destinations'
      fullPath: '/destinations/'
      preLoaderRoute: typeof DestinationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals/': {
      id: '/deals/'
      path: '/deals'
      fullPath: '/deals/'
      preLoaderRoute: typeof DealsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/': {
      id: '/business/'
      path: '/business'
      fullPath: '/business/'
      preLoaderRoute: typeof BusinessIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/videos': {
      id: '/studio/videos'
      path: '/videos'
      fullPath: '/studio/videos'
      preLoaderRoute: typeof StudioVideosRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/threads': {
      id: '/studio/threads'
      path: '/threads'
      fullPath: '/studio/threads'
      preLoaderRoute: typeof StudioThreadsRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/schedule': {
      id: '/studio/schedule'
      path: '/schedule'
      fullPath: '/studio/schedule'
      preLoaderRoute: typeof StudioScheduleRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/links': {
      id: '/studio/links'
      path: '/links'
      fullPath: '/studio/links'
      preLoaderRoute: typeof StudioLinksRouteImport
      parentRoute: typeof StudioRoute
    }
    '/sounds/$id': {
      id: '/sounds/$id'
      path: '/sounds/$id'
      fullPath: '/sounds/$id'
      preLoaderRoute: typeof SoundsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/$bookingId': {
      id: '/review/$bookingId'
      path: '/review/$bookingId'
      fullPath: '/review/$bookingId'
      preLoaderRoute: typeof ReviewBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$code': {
      id: '/r/$code'
      path: '/r/$code'
      fullPath: '/r/$code'
      preLoaderRoute: typeof RCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/dmca': {
      id: '/legal/dmca'
      path: '/legal/dmca'
      fullPath: '/legal/dmca'
      preLoaderRoute: typeof LegalDmcaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/creator-agreement': {
      id: '/legal/creator-agreement'
      path: '/legal/creator-agreement'
      fullPath: '/legal/creator-agreement'
      preLoaderRoute: typeof LegalCreatorAgreementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/legal/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/business-agreement': {
      id: '/legal/business-agreement'
      path: '/legal/business-agreement'
      fullPath: '/legal/business-agreement'
      preLoaderRoute: typeof LegalBusinessAgreementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itineraries/new': {
      id: '/itineraries/new'
      path: '/itineraries/new'
      fullPath: '/itineraries/new'
      preLoaderRoute: typeof ItinerariesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itineraries/$id': {
      id: '/itineraries/$id'
      path: '/itineraries/$id'
      fullPath: '/itineraries/$id'
      preLoaderRoute: typeof ItinerariesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed/playlist': {
      id: '/feed/playlist'
      path: '/feed/playlist'
      fullPath: '/feed/playlist'
      preLoaderRoute: typeof FeedPlaylistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals/$id': {
      id: '/deals/$id'
      path: '/deals/$id'
      fullPath: '/deals/$id'
      preLoaderRoute: typeof DealsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/earnings': {
      id: '/creator/earnings'
      path: '/creator/earnings'
      fullPath: '/creator/earnings'
      preLoaderRoute: typeof CreatorEarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/calculator': {
      id: '/creator/calculator'
      path: '/creator/calculator'
      fullPath: '/creator/calculator'
      preLoaderRoute: typeof CreatorCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/applications': {
      id: '/creator/applications'
      path: '/creator/applications'
      fullPath: '/creator/applications'
      preLoaderRoute: typeof CreatorApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/analytics': {
      id: '/creator/analytics'
      path: '/creator/analytics'
      fullPath: '/creator/analytics'
      preLoaderRoute: typeof CreatorAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$id': {
      id: '/collections/$id'
      path: '/$id'
      fullPath: '/collections/$id'
      preLoaderRoute: typeof CollectionsIdRouteImport
      parentRoute: typeof CollectionsRoute
    }
    '/collab/$code': {
      id: '/collab/$code'
      path: '/collab/$code'
      fullPath: '/collab/$code'
      preLoaderRoute: typeof CollabCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/threads': {
      id: '/business/threads'
      path: '/business/threads'
      fullPath: '/business/threads'
      preLoaderRoute: typeof BusinessThreadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/signup': {
      id: '/business/signup'
      path: '/business/signup'
      fullPath: '/business/signup'
      preLoaderRoute: typeof BusinessSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/redemptions': {
      id: '/business/redemptions'
      path: '/business/redemptions'
      fullPath: '/business/redemptions'
      preLoaderRoute: typeof BusinessRedemptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/price-audit': {
      id: '/business/price-audit'
      path: '/business/price-audit'
      fullPath: '/business/price-audit'
      preLoaderRoute: typeof BusinessPriceAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/photos': {
      id: '/business/photos'
      path: '/business/photos'
      fullPath: '/business/photos'
      preLoaderRoute: typeof BusinessPhotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/collabs': {
      id: '/business/collabs'
      path: '/business/collabs'
      fullPath: '/business/collabs'
      preLoaderRoute: typeof BusinessCollabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/calculator': {
      id: '/business/calculator'
      path: '/business/calculator'
      fullPath: '/business/calculator'
      preLoaderRoute: typeof BusinessCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/apply': {
      id: '/business/apply'
      path: '/business/apply'
      fullPath: '/business/apply'
      preLoaderRoute: typeof BusinessApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/applications': {
      id: '/business/applications'
      path: '/business/applications'
      fullPath: '/business/applications'
      preLoaderRoute: typeof BusinessApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/return': {
      id: '/book/return'
      path: '/book/return'
      fullPath: '/book/return'
      preLoaderRoute: typeof BookReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$dealId': {
      id: '/book/$dealId'
      path: '/book/$dealId'
      fullPath: '/book/$dealId'
      preLoaderRoute: typeof BookDealIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/videos': {
      id: '/admin/videos'
      path: '/videos'
      fullPath: '/admin/videos'
      preLoaderRoute: typeof AdminVideosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/seed': {
      id: '/admin/seed'
      path: '/seed'
      fullPath: '/admin/seed'
      preLoaderRoute: typeof AdminSeedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payouts': {
      id: '/admin/payouts'
      path: '/payouts'
      fullPath: '/admin/payouts'
      preLoaderRoute: typeof AdminPayoutsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/moderation': {
      id: '/admin/moderation'
      path: '/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AdminModerationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/investor': {
      id: '/admin/investor'
      path: '/investor'
      fullPath: '/admin/investor'
      preLoaderRoute: typeof AdminInvestorRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/errors': {
      id: '/admin/errors'
      path: '/errors'
      fullPath: '/admin/errors'
      preLoaderRoute: typeof AdminErrorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/disputes': {
      id: '/admin/disputes'
      path: '/disputes'
      fullPath: '/admin/disputes'
      preLoaderRoute: typeof AdminDisputesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/discoveries': {
      id: '/admin/discoveries'
      path: '/discoveries'
      fullPath: '/admin/discoveries'
      preLoaderRoute: typeof AdminDiscoveriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/deals': {
      id: '/admin/deals'
      path: '/deals'
      fullPath: '/admin/deals'
      preLoaderRoute: typeof AdminDealsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/connect': {
      id: '/admin/connect'
      path: '/connect'
      fullPath: '/admin/connect'
      preLoaderRoute: typeof AdminConnectRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/delete': {
      id: '/account/delete'
      path: '/account/delete'
      fullPath: '/account/delete'
      preLoaderRoute: typeof AccountDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/$country/': {
      id: '/destinations/$country/'
      path: '/destinations/$country'
      fullPath: '/destinations/$country/'
      preLoaderRoute: typeof DestinationsCountryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/videos/$id': {
      id: '/studio/videos/$id'
      path: '/$id'
      fullPath: '/studio/videos/$id'
      preLoaderRoute: typeof StudioVideosIdRouteImport
      parentRoute: typeof StudioVideosRoute
    }
    '/studio/threads/$id': {
      id: '/studio/threads/$id'
      path: '/$id'
      fullPath: '/studio/threads/$id'
      preLoaderRoute: typeof StudioThreadsIdRouteImport
      parentRoute: typeof StudioThreadsRoute
    }
    '/review/$bookingId/thanks': {
      id: '/review/$bookingId/thanks'
      path: '/thanks'
      fullPath: '/review/$bookingId/thanks'
      preLoaderRoute: typeof ReviewBookingIdThanksRouteImport
      parentRoute: typeof ReviewBookingIdRoute
    }
    '/lovable/email/unsubscribe': {
      id: '/lovable/email/unsubscribe'
      path: '/lovable/email/unsubscribe'
      fullPath: '/lovable/email/unsubscribe'
      preLoaderRoute: typeof LovableEmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/$country/$city': {
      id: '/destinations/$country/$city'
      path: '/destinations/$country/$city'
      fullPath: '/destinations/$country/$city'
      preLoaderRoute: typeof DestinationsCountryCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/threads/$id': {
      id: '/business/threads/$id'
      path: '/$id'
      fullPath: '/business/threads/$id'
      preLoaderRoute: typeof BusinessThreadsIdRouteImport
      parentRoute: typeof BusinessThreadsRoute
    }
    '/business/onboarding/website': {
      id: '/business/onboarding/website'
      path: '/business/onboarding/website'
      fullPath: '/business/onboarding/website'
      preLoaderRoute: typeof BusinessOnboardingWebsiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/onboarding/payout': {
      id: '/business/onboarding/payout'
      path: '/business/onboarding/payout'
      fullPath: '/business/onboarding/payout'
      preLoaderRoute: typeof BusinessOnboardingPayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/invite/$token': {
      id: '/business/invite/$token'
      path: '/business/invite/$token'
      fullPath: '/business/invite/$token'
      preLoaderRoute: typeof BusinessInviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/deals/new': {
      id: '/business/deals/new'
      path: '/business/deals/new'
      fullPath: '/business/deals/new'
      preLoaderRoute: typeof BusinessDealsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/deals/$id': {
      id: '/business/deals/$id'
      path: '/business/deals/$id'
      fullPath: '/business/deals/$id'
      preLoaderRoute: typeof BusinessDealsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/match/$code': {
      id: '/book/match/$code'
      path: '/book/match/$code'
      fullPath: '/book/match/$code'
      preLoaderRoute: typeof BookMatchCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mux-webhook': {
      id: '/api/public/mux-webhook'
      path: '/api/public/mux-webhook'
      fullPath: '/api/public/mux-webhook'
      preLoaderRoute: typeof ApiPublicMuxWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/attribute': {
      id: '/api/public/attribute'
      path: '/api/public/attribute'
      fullPath: '/api/public/attribute'
      preLoaderRoute: typeof ApiPublicAttributeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/deals/$id/': {
      id: '/business/deals/$id/'
      path: '/'
      fullPath: '/business/deals/$id/'
      preLoaderRoute: typeof BusinessDealsIdIndexRouteImport
      parentRoute: typeof BusinessDealsIdRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/deals/$id/edit': {
      id: '/business/deals/$id/edit'
      path: '/edit'
      fullPath: '/business/deals/$id/edit'
      preLoaderRoute: typeof BusinessDealsIdEditRouteImport
      parentRoute: typeof BusinessDealsIdRoute
    }
    '/book/match/$code/thanks': {
      id: '/book/match/$code/thanks'
      path: '/thanks'
      fullPath: '/book/match/$code/thanks'
      preLoaderRoute: typeof BookMatchCodeThanksRouteImport
      parentRoute: typeof BookMatchCodeRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-external-calendars': {
      id: '/api/public/hooks/sync-external-calendars'
      path: '/api/public/hooks/sync-external-calendars'
      fullPath: '/api/public/hooks/sync-external-calendars'
      preLoaderRoute: typeof ApiPublicHooksSyncExternalCalendarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/go/$id': {
      id: '/api/public/go/$id'
      path: '/api/public/go/$id'
      fullPath: '/api/public/go/$id'
      preLoaderRoute: typeof ApiPublicGoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/d/$id': {
      id: '/api/public/d/$id'
      path: '/api/public/d/$id'
      fullPath: '/api/public/d/$id'
      preLoaderRoute: typeof ApiPublicDIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/sync-youtube': {
      id: '/api/public/cron/sync-youtube'
      path: '/api/public/cron/sync-youtube'
      fullPath: '/api/public/cron/sync-youtube'
      preLoaderRoute: typeof ApiPublicCronSyncYoutubeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/sync-tiktok': {
      id: '/api/public/cron/sync-tiktok'
      path: '/api/public/cron/sync-tiktok'
      fullPath: '/api/public/cron/sync-tiktok'
      preLoaderRoute: typeof ApiPublicCronSyncTiktokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/review-prompts': {
      id: '/api/public/cron/review-prompts'
      path: '/api/public/cron/review-prompts'
      fullPath: '/api/public/cron/review-prompts'
      preLoaderRoute: typeof ApiPublicCronReviewPromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/refresh-creator-tiers': {
      id: '/api/public/cron/refresh-creator-tiers'
      path: '/api/public/cron/refresh-creator-tiers'
      fullPath: '/api/public/cron/refresh-creator-tiers'
      preLoaderRoute: typeof ApiPublicCronRefreshCreatorTiersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/parity-sweep': {
      id: '/api/public/cron/parity-sweep'
      path: '/api/public/cron/parity-sweep'
      fullPath: '/api/public/cron/parity-sweep'
      preLoaderRoute: typeof ApiPublicCronParitySweepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/fx-refresh': {
      id: '/api/public/cron/fx-refresh'
      path: '/api/public/cron/fx-refresh'
      fullPath: '/api/public/cron/fx-refresh'
      preLoaderRoute: typeof ApiPublicCronFxRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/expiring-deals': {
      id: '/api/public/cron/expiring-deals'
      path: '/api/public/cron/expiring-deals'
      fullPath: '/api/public/cron/expiring-deals'
      preLoaderRoute: typeof ApiPublicCronExpiringDealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/discover-deals': {
      id: '/api/public/cron/discover-deals'
      path: '/api/public/cron/discover-deals'
      fullPath: '/api/public/cron/discover-deals'
      preLoaderRoute: typeof ApiPublicCronDiscoverDealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/business-digest': {
      id: '/api/public/cron/business-digest'
      path: '/api/public/cron/business-digest'
      fullPath: '/api/public/cron/business-digest'
      preLoaderRoute: typeof ApiPublicCronBusinessDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/b/$id': {
      id: '/api/public/b/$id'
      path: '/api/public/b/$id'
      fullPath: '/api/public/b/$id'
      preLoaderRoute: typeof ApiPublicBIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ical/deal/$dealId/$token.ics': {
      id: '/api/public/ical/deal/$dealId/$token.ics'
      path: '/api/public/ical/deal/$dealId/$token.ics'
      fullPath: '/api/public/ical/deal/$dealId/$token.ics'
      preLoaderRoute: typeof ApiPublicIcalDealDealIdTokenDoticsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminConnectRoute: typeof AdminConnectRoute
  AdminDealsRoute: typeof AdminDealsRoute
  AdminDiscoveriesRoute: typeof AdminDiscoveriesRoute
  AdminDisputesRoute: typeof AdminDisputesRoute
  AdminErrorsRoute: typeof AdminErrorsRoute
  AdminInvestorRoute: typeof AdminInvestorRoute
  AdminModerationRoute: typeof AdminModerationRoute
  AdminPayoutsRoute: typeof AdminPayoutsRoute
  AdminSeedRoute: typeof AdminSeedRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVideosRoute: typeof AdminVideosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminConnectRoute: AdminConnectRoute,
  AdminDealsRoute: AdminDealsRoute,
  AdminDiscoveriesRoute: AdminDiscoveriesRoute,
  AdminDisputesRoute: AdminDisputesRoute,
  AdminErrorsRoute: AdminErrorsRoute,
  AdminInvestorRoute: AdminInvestorRoute,
  AdminModerationRoute: AdminModerationRoute,
  AdminPayoutsRoute: AdminPayoutsRoute,
  AdminSeedRoute: AdminSeedRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVideosRoute: AdminVideosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CollectionsRouteChildren {
  CollectionsIdRoute: typeof CollectionsIdRoute
}

const CollectionsRouteChildren: CollectionsRouteChildren = {
  CollectionsIdRoute: CollectionsIdRoute,
}

const CollectionsRouteWithChildren = CollectionsRoute._addFileChildren(
  CollectionsRouteChildren,
)

interface StudioThreadsRouteChildren {
  StudioThreadsIdRoute: typeof StudioThreadsIdRoute
}

const StudioThreadsRouteChildren: StudioThreadsRouteChildren = {
  StudioThreadsIdRoute: StudioThreadsIdRoute,
}

const StudioThreadsRouteWithChildren = StudioThreadsRoute._addFileChildren(
  StudioThreadsRouteChildren,
)

interface StudioVideosRouteChildren {
  StudioVideosIdRoute: typeof StudioVideosIdRoute
}

const StudioVideosRouteChildren: StudioVideosRouteChildren = {
  StudioVideosIdRoute: StudioVideosIdRoute,
}

const StudioVideosRouteWithChildren = StudioVideosRoute._addFileChildren(
  StudioVideosRouteChildren,
)

interface StudioRouteChildren {
  StudioLinksRoute: typeof StudioLinksRoute
  StudioScheduleRoute: typeof StudioScheduleRoute
  StudioThreadsRoute: typeof StudioThreadsRouteWithChildren
  StudioVideosRoute: typeof StudioVideosRouteWithChildren
  StudioIndexRoute: typeof StudioIndexRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioLinksRoute: StudioLinksRoute,
  StudioScheduleRoute: StudioScheduleRoute,
  StudioThreadsRoute: StudioThreadsRouteWithChildren,
  StudioVideosRoute: StudioVideosRouteWithChildren,
  StudioIndexRoute: StudioIndexRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

interface BusinessThreadsRouteChildren {
  BusinessThreadsIdRoute: typeof BusinessThreadsIdRoute
}

const BusinessThreadsRouteChildren: BusinessThreadsRouteChildren = {
  BusinessThreadsIdRoute: BusinessThreadsIdRoute,
}

const BusinessThreadsRouteWithChildren = BusinessThreadsRoute._addFileChildren(
  BusinessThreadsRouteChildren,
)

interface ReviewBookingIdRouteChildren {
  ReviewBookingIdThanksRoute: typeof ReviewBookingIdThanksRoute
}

const ReviewBookingIdRouteChildren: ReviewBookingIdRouteChildren = {
  ReviewBookingIdThanksRoute: ReviewBookingIdThanksRoute,
}

const ReviewBookingIdRouteWithChildren = ReviewBookingIdRoute._addFileChildren(
  ReviewBookingIdRouteChildren,
)

interface BookMatchCodeRouteChildren {
  BookMatchCodeThanksRoute: typeof BookMatchCodeThanksRoute
}

const BookMatchCodeRouteChildren: BookMatchCodeRouteChildren = {
  BookMatchCodeThanksRoute: BookMatchCodeThanksRoute,
}

const BookMatchCodeRouteWithChildren = BookMatchCodeRoute._addFileChildren(
  BookMatchCodeRouteChildren,
)

interface BusinessDealsIdRouteChildren {
  BusinessDealsIdEditRoute: typeof BusinessDealsIdEditRoute
  BusinessDealsIdIndexRoute: typeof BusinessDealsIdIndexRoute
}

const BusinessDealsIdRouteChildren: BusinessDealsIdRouteChildren = {
  BusinessDealsIdEditRoute: BusinessDealsIdEditRoute,
  BusinessDealsIdIndexRoute: BusinessDealsIdIndexRoute,
}

const BusinessDealsIdRouteWithChildren = BusinessDealsIdRoute._addFileChildren(
  BusinessDealsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CollectionsRoute: CollectionsRouteWithChildren,
  CreateRoute: CreateRoute,
  DownloadRoute: DownloadRoute,
  InvestRoute: InvestRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StudioRoute: StudioRouteWithChildren,
  SupportRoute: SupportRoute,
  WelcomeRoute: WelcomeRoute,
  AccountDeleteRoute: AccountDeleteRoute,
  BookDealIdRoute: BookDealIdRoute,
  BookReturnRoute: BookReturnRoute,
  BusinessApplicationsRoute: BusinessApplicationsRoute,
  BusinessApplyRoute: BusinessApplyRoute,
  BusinessCalculatorRoute: BusinessCalculatorRoute,
  BusinessCollabsRoute: BusinessCollabsRoute,
  BusinessPhotosRoute: BusinessPhotosRoute,
  BusinessPriceAuditRoute: BusinessPriceAuditRoute,
  BusinessRedemptionsRoute: BusinessRedemptionsRoute,
  BusinessSignupRoute: BusinessSignupRoute,
  BusinessThreadsRoute: BusinessThreadsRouteWithChildren,
  CollabCodeRoute: CollabCodeRoute,
  CreatorAnalyticsRoute: CreatorAnalyticsRoute,
  CreatorApplicationsRoute: CreatorApplicationsRoute,
  CreatorCalculatorRoute: CreatorCalculatorRoute,
  CreatorEarningsRoute: CreatorEarningsRoute,
  DealsIdRoute: DealsIdRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  FeedPlaylistRoute: FeedPlaylistRoute,
  ItinerariesIdRoute: ItinerariesIdRoute,
  ItinerariesNewRoute: ItinerariesNewRoute,
  LegalBusinessAgreementRoute: LegalBusinessAgreementRoute,
  LegalCookiesRoute: LegalCookiesRoute,
  LegalCreatorAgreementRoute: LegalCreatorAgreementRoute,
  LegalDmcaRoute: LegalDmcaRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  RCodeRoute: RCodeRoute,
  ReviewBookingIdRoute: ReviewBookingIdRouteWithChildren,
  SoundsIdRoute: SoundsIdRoute,
  UUsernameRoute: UUsernameRoute,
  BusinessIndexRoute: BusinessIndexRoute,
  DealsIndexRoute: DealsIndexRoute,
  DestinationsIndexRoute: DestinationsIndexRoute,
  ItinerariesIndexRoute: ItinerariesIndexRoute,
  LegalIndexRoute: LegalIndexRoute,
  ApiPublicAttributeRoute: ApiPublicAttributeRoute,
  ApiPublicMuxWebhookRoute: ApiPublicMuxWebhookRoute,
  BookMatchCodeRoute: BookMatchCodeRouteWithChildren,
  BusinessDealsIdRoute: BusinessDealsIdRouteWithChildren,
  BusinessDealsNewRoute: BusinessDealsNewRoute,
  BusinessInviteTokenRoute: BusinessInviteTokenRoute,
  BusinessOnboardingPayoutRoute: BusinessOnboardingPayoutRoute,
  BusinessOnboardingWebsiteRoute: BusinessOnboardingWebsiteRoute,
  DestinationsCountryCityRoute: DestinationsCountryCityRoute,
  LovableEmailUnsubscribeRoute: LovableEmailUnsubscribeRoute,
  DestinationsCountryIndexRoute: DestinationsCountryIndexRoute,
  ApiPublicBIdRoute: ApiPublicBIdRoute,
  ApiPublicCronBusinessDigestRoute: ApiPublicCronBusinessDigestRoute,
  ApiPublicCronDiscoverDealsRoute: ApiPublicCronDiscoverDealsRoute,
  ApiPublicCronExpiringDealsRoute: ApiPublicCronExpiringDealsRoute,
  ApiPublicCronFxRefreshRoute: ApiPublicCronFxRefreshRoute,
  ApiPublicCronParitySweepRoute: ApiPublicCronParitySweepRoute,
  ApiPublicCronRefreshCreatorTiersRoute: ApiPublicCronRefreshCreatorTiersRoute,
  ApiPublicCronReviewPromptsRoute: ApiPublicCronReviewPromptsRoute,
  ApiPublicCronSyncTiktokRoute: ApiPublicCronSyncTiktokRoute,
  ApiPublicCronSyncYoutubeRoute: ApiPublicCronSyncYoutubeRoute,
  ApiPublicDIdRoute: ApiPublicDIdRoute,
  ApiPublicGoIdRoute: ApiPublicGoIdRoute,
  ApiPublicHooksSyncExternalCalendarsRoute:
    ApiPublicHooksSyncExternalCalendarsRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  ApiPublicIcalDealDealIdTokenDoticsRoute:
    ApiPublicIcalDealDealIdTokenDoticsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
